import {getCostSummary} from '../cost/tracker.js';
import {config} from '../config.js';
import {igResearch} from '../integrations/igResearch.js';
import {igAnalysisMemory} from '../integrations/igAnalysisMemory.js';
import {listIgImportedSignals} from '../integrations/igImportedSignals.js';
import type http from 'node:http';
import {WebSocketServer,WebSocket} from 'ws';
import {randomUUID} from 'node:crypto';
import {igStreaming,type createIgStreaming} from '../integrations/igStreaming.js';
import {getIgWorkspace} from '../integrations/igWorkspace.js';
import {getIgOrderState,getIgBrokerPending} from '../integrations/igOrders.js';
import {listIgSchedules} from '../integrations/igSchedules.js';
import {igPreferences} from '../integrations/igPreferences.js';
import {getIgStatus,type IgEnvironment} from '../integrations/igConnection.js';
import {igEvents} from '../integrations/igEvents.js';
export async function readIgView(mode:IgEnvironment){const w=await getIgWorkspace(mode),o=getIgOrderState(mode,w.positions),b=await getIgBrokerPending(mode,w.connection.connectionGeneration??undefined),cost=await getCostSummary({dailyCapUsd:config.costCap.dailyUsd,weeklyCapUsd:config.costCap.weeklyUsd});if(getIgStatus().environments[mode].connectionGeneration!==w.connection.connectionGeneration)throw Error('IG-kontot ändrades under hämtningen');let researchRevision=null;try{researchRevision=igResearch.view(mode).revision;}catch{/* Forskning får inte blockera handelsytans avstämning. */}return {...w,...o,cost,researchRevision,pendingOrders:[...o.pendingOrders.filter(d=>!b.orders.some((p:any)=>p.dealId===d.dealId)),...b.orders],pendingOrderStatus:b.status,signalProposals:w.pendingOrders,analysisMemory:igAnalysisMemory.summary(mode),importedSignals:listIgImportedSignals(mode),preferences:igPreferences.get(mode),schedules:listIgSchedules(mode),streaming:igStreaming.summary(mode),transport:'WebSocket · IG Lightstreamer; REST för snapshot/metadata',positions:w.positions?.map((p:any)=>{const plan=o.exitPlans.find(x=>x.dealId===p.dealId);return {...p,closeAt:plan?.closeAt,closing:plan?.status==='submitted'||plan?.status==='unknown',closeError:plan?.error,closeStatus:plan?.status};})};}
export function attachIgRealtime(server:http.Server,deps:{authorize:(req:http.IncomingMessage)=>Promise<boolean>;snapshot?:(mode:IgEnvironment)=>Promise<any>;stream?:ReturnType<typeof createIgStreaming>;intervalMs?:number}){
 const stream=deps.stream??igStreaming,snapshot=deps.snapshot??readIgView,wss=new WebSocketServer({noServer:true,maxPayload:8192});const epoch=randomUUID();let sequence=0,closed=false;
 const clients=new Map<WebSocket,{req:http.IncomingMessage;mode:IgEnvironment;epics:string[];charts:{epic:string;scale:string}[];alive:boolean;authorization:string|null;messages:number;window:number}>(),refreshing=new Set<IgEnvironment>(),dirty=new Set<IgEnvironment>();
 function send(ws:WebSocket,mode:IgEnvironment,type:string,data:unknown){if(ws.readyState!==WebSocket.OPEN)return;if(ws.bufferedAmount>1024*1024){ws.close(1013,'För långsam klient');return;}ws.send(JSON.stringify({epoch,sequence:++sequence,environment:mode,type,sentAt:Date.now(),data}));}
 function broadcast(mode:IgEnvironment,type:string,data:unknown){for(const [ws,c] of clients)if(c.mode===mode)send(ws,mode,type,data);}
 function subscriptions(mode:IgEnvironment){const own=[...clients.values()].filter(c=>c.mode===mode),epics=[...new Set(own.flatMap(c=>c.epics))];const charts=[...new Map(own.flatMap(c=>c.charts).map(c=>[`${c.epic}:${c.scale}`,c])).values()];stream.ensure(mode,epics,charts);}
 async function refresh(mode:IgEnvironment){if(closed||![...clients.values()].some(c=>c.mode===mode))return;if(refreshing.has(mode)){dirty.add(mode);return;}refreshing.add(mode);try{const w=await snapshot(mode);broadcast(mode,'snapshot',w);}catch{broadcast(mode,'sync-error',{message:'IG-underlaget kunde inte avstämmas; nya order kräver färskt underlag'});}finally{refreshing.delete(mode);if(dirty.delete(mode))queueMicrotask(()=>void refresh(mode));}}
 const onUpgrade=async(req:http.IncomingMessage,socket:any,head:Buffer)=>{try{const url=new URL(req.url??'/','http://localhost');if(url.pathname!=='/api/ig/realtime'){socket.destroy();return;}const mode=url.searchParams.get('environment');if(mode!=='demo'&&mode!=='live'||clients.size>=16||!await deps.authorize(req)){socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');socket.destroy();return;}if(socket.destroyed)return;wss.handleUpgrade(req,socket,head,ws=>{const c={req,mode:mode as IgEnvironment,epics:[] as string[],charts:[] as {epic:string;scale:string}[],alive:true,authorization:req.headers.cookie??null,messages:0,window:Date.now()};clients.set(ws,c);ws.on('error',()=>ws.terminate());ws.on('pong',()=>{c.alive=true;});ws.on('message',raw=>{try{if(Date.now()-c.window>10000){c.messages=0;c.window=Date.now();}if(++c.messages>30){ws.close(1008,'För många meddelanden');return;}const m=JSON.parse(raw.toString());if(m.type==='ping'){send(ws,c.mode,'pong',{echo:m.at});return;}if(m.type!=='subscribe'||!Array.isArray(m.epics)||m.epics.length>30||m.epics.some((e:any)=>typeof e!=='string'||!/^[A-Za-z0-9._-]{1,100}$/.test(e)))throw Error('shape');const charts=m.charts??(m.chart?[m.chart]:[]);if(!Array.isArray(charts)||charts.length>4||charts.some((x:any)=>!x||!m.epics.includes(x.epic)||!['1MINUTE','5MINUTE','HOUR'].includes(x.scale)))throw Error('chart');const others=[...clients.values()].filter(x=>x!==c&&x.mode===c.mode);if(new Set([...others.flatMap(x=>x.epics),...m.epics]).size>30||new Set([...others.flatMap(x=>x.charts).map(x=>`${x.epic}:${x.scale}`),...charts.map((x:any)=>`${x.epic}:${x.scale}`)]).size>4){send(ws,c.mode,'subscription-error',{message:'IG-streamingpoolen är full: högst 30 instrument och 4 diagram delas mellan öppna vyer'});return;}c.epics=[...new Set(m.epics)] as string[];c.charts=charts.map((x:any)=>({epic:x.epic,scale:x.scale}));subscriptions(c.mode);send(ws,c.mode,'stream-status',stream.summary(c.mode));for(const q of stream.quotes(c.mode))if(c.epics.includes(q.epic))send(ws,c.mode,'quote',q);}catch{ws.close(1008,'Ogiltig prenumeration');}});ws.on('close',()=>{clients.delete(ws);subscriptions(c.mode);});send(ws,c.mode,'hello',{transport:'WebSocket',epoch});void refresh(c.mode);});}catch{socket.destroy();}};
 server.on('upgrade',onUpgrade);
 const listeners=(['quote','candle','account','status','trade'] as const).map(kind=>{const fn=(mode:IgEnvironment,data:any)=>{if(kind==='quote'||kind==='candle'){for(const [ws,c] of clients)if(c.mode===mode&&c.epics.includes(data.epic))send(ws,mode,kind,data);}else{broadcast(mode,kind==='status'?'stream-status':kind,data);if(kind==='trade')void refresh(mode);}};stream.events.on(kind,fn);return {kind,fn};});
 const changed=(mode:IgEnvironment)=>{subscriptions(mode);void refresh(mode);};igEvents.on('changed',changed);
 let checking=false;const timer=setInterval(async()=>{if(checking||closed)return;checking=true;try{for(const [ws,c] of clients){let authorized=false;try{authorized=await deps.authorize(c.req);}catch{}if(!c.alive||!authorized){ws.close(1008,'Sessionen kan inte verifieras');continue;}c.alive=false;ws.ping();send(ws,c.mode,'stream-status',stream.summary(c.mode));}for(const mode of ['demo','live'] as const){subscriptions(mode);void refresh(mode);}}finally{checking=false;}},deps.intervalMs??15000);timer.unref();
 function close(){closed=true;clearInterval(timer);server.off('upgrade',onUpgrade);igEvents.off('changed',changed);for(const {kind,fn}of listeners)stream.events.off(kind,fn);for(const ws of clients.keys())ws.terminate();wss.close();stream.close();}
 server.once('close',close);
 return {refresh,broadcast,close,revoke:(cookie:string|undefined)=>{if(cookie)for(const [ws,c]of clients)if(c.authorization===cookie)ws.close(1008,'Utloggad');}};
}
