// Forskningsmetadata från användarens underlag. Ingen signalmotor eller orderaktivering.
const common={version:1,kind:'research_candidate',executable:false,status:'needs_source',availability:'blocked_missing_source',checked:false,enabled:false,timeframe:'1h',warmupBars:null,direction:'not_verified',sizing:null,costs:null,entry:null,exit:null,stop:null};
const source={provider:'AITradingArena / DaviddTech',url:'https://aitradingarena.com/',document:'reference/strategyfactory/tradingstrategier-granskning.md',reviewedDate:'2026-10-08',verification:'extern rapport; ej reproducerad eller verifierad för IG'};
const notes=['Forskningskandidat, inte körbar eller aktiverad. Originalkod, exakta inputs och affärslista måste verifieras.','Rapporterade procent/PF/nedgång är externa historiska testresultat, inte IG-resultat eller vinstprognoser. Testperiod och kapital-/kostnadsmodell är inte fullt identifierade.','1h-diagram bevisar inte lönsamhet med 1–5 minuters innehav. IG-priser, spread, kontraktsstorlek och tillgänglighet måste testas separat.'];
export const strategyFactoryCandidates=[
 {...common,id:'strategyfactory-casc-stx',name:'CASC–STX · StrategyFactory',instrument:'STX (extern testmarknad)',source:{...source,variantId:'gpt6-casc-link-stx-95352493'},reportedResults:{netPercent:191.9,profitFactor:1.98,maxDrawdownPercent:16.4,trades:105,period:null,currency:null,verifiedForIg:false},notes:[...notes,'Fullständiga signalformler och input-export saknas. Grundkortets parameterstudier bevisar inte STX-variantens regler.']},
 {...common,id:'strategyfactory-ttf-mnt',name:'TTF–MNT · StrategyFactory',instrument:'MNT (extern testmarknad)',source:{...source,variantId:'gpt6-gpt6-gpt6-t3-ttf-reignite-v1-mnt-666645fc-mnt-c0fa47c3'},reportedResults:{netPercent:274.7,profitFactor:1.78,maxDrawdownPercent:24.6,trades:134,period:null,currency:null,verifiedForIg:false},notes:[...notes,'Senare rapport: +256,8 %, PF1,69,135 affärer; konfiguration behöver matchas. Full signalformel saknas.']},
 {...common,id:'strategyfactory-vqzla-ena',name:'VQZLA–ENA · StrategyFactory',instrument:'ENA (extern testmarknad)',source:{...source,variantId:'gpt6-t3-vqzla-reignite-v1-ena-bb1d3b6e'},reportedResults:{netPercent:131.8,profitFactor:1.73,maxDrawdownPercent:16.3,trades:131,period:null,currency:null,verifiedForIg:false},notes:[...notes,'Rapporterade senare körningar är konsekventa; tillräckligt oberoende framåttest och full signalformel saknas.']},
 {...common,id:'strategyfactory-donb-doge',name:'DONB–DOGE · StrategyFactory',instrument:'DOGEUSDT perpetual (extern testmarknad)',source:{...source,variantId:'daviddtech-crypto-donb-btc'},reportedResults:{netPercent:144.6,profitFactor:1.82,maxDrawdownPercent:8.6,trades:110,period:null,currency:null,verifiedForIg:false},documentedParameters:{donchianPeriod:28,volatilityFloor:0.95,emaPeriod:105,atrStopMultiplier:4,longTargetR:2.6,shortTargetR:1.2,atrPeriod:null},notes:[...notes,'Donchian-utbrott med ATR-volatilitetsfilter och EMA-trend. Floor-formel/enhet, ATR-period och kanalens signal-/ljusdefinition måste bekräftas.','Senare annan körning PF1,01 och DD90,6%; kod/parametrar måste matchas innan jämförelse.']},
 {...common,id:'strategyfactory-plbk',name:'PLBK · StrategyFactory',instrument:'SOL/ETH-familj (extern testmarknad)',source:{...source,variantId:'daviddtech-crypto-plbk-sol'},reportedResults:{netPercent:47,profitFactor:1.77,maxDrawdownPercent:4.5,trades:110,period:'ETH-körning 2026-08-29; full testperiod okänd',currency:null,verifiedForIg:false},documentedParameters:{lenT3PLBK:140,vfT3PLBK:0.55,rsiLenQQEPLBK:16,smoothQQEPLBK:8,factQQEPLBK:5.25,pullDepthPLBK:6.5,useChopPLBK:true,chopLenPLBK:15,chopThreshPLBK:61,ATR_LEN:13,ATR_RISK_MULT:2.475,PROFIT_FACTOR_LONG:1.4,PROFIT_FACTOR_SHORT:1.15,RISK_LEVERAGE:3},documentedConcept:{long:'Close över stigande T3; CHOP-filter godkänt; QQE först under50−pullDepth, därefter korsning upp genom följelinje.',short:'Spegelvänd konceptlogik; exakta regler ej verifierade.',missing:['QQE-formel','Rekylminnets återställning','Exakt motor och exekvering','Matchning SOL-parametrar mot ETH-resultat']},notes:[...notes,'Parametrarna är dokumenterade för SOL-varianten; resultatet PF1,77 tillhör ETH och får inte tillskrivas dessa inputs utan verifiering.','Lämplig för märkt rekonstruktion; ingen sådan körbar rekonstruktion är implementerad här.']}
] as const;
