import fs from 'node:fs';
import {strategyFactoryCandidates} from '../src/integrations/igStrategyFactory.js';
const apply=process.argv.includes('--apply');
const origin=new URL(process.env.IG_LIBRARY_ORIGIN??'https://aiupscale-dator1.tail64d627.ts.net:9443');
if(origin.protocol!=='https:'||!origin.hostname.endsWith('.ts.net')||origin.username||origin.password||origin.pathname!=='/'||origin.search||origin.hash)throw Error('Använd befintlig HTTPS-adress inom Tailscale');
async function api(route:string,body?:any){const r=await fetch(new URL(route,origin),{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json',Origin:origin.origin}:{},body:body?JSON.stringify(body):undefined});const x:any=await r.json();if(!r.ok||x.error)throw Error(x.error??`HTTP${r.status}`);return x;}
const content=fs.readFileSync(new URL('../reference/strategyfactory/tradingstrategier-granskning.md',import.meta.url),'utf8');if(Buffer.byteLength(content)>20000)throw Error('Underlaget är större än bibliotekets filgräns');
const modes=['demo','live'] as const,views=new Map<string,any>();
for(const mode of modes){if(process.argv.includes('--connect')){const status=await api('/api/ig/connect',{environment:mode});if(status.environments?.[mode]?.status!=='connected')throw Error(`${mode}: IG kunde inte anslutas; inget bibliotek har importerats.`);}const view=await api(`/api/ig/research?environment=${mode}`);for(const c of strategyFactoryCandidates)if(!view.baselines.some((b:any)=>b.id===c.id&&b.kind==='research_candidate'&&b.executable===false))throw Error(`${mode}: StrategyFactory-registret är inte uppdaterat; inga poster har importerats.`);views.set(mode,view);}
for(const mode of modes){let view=views.get(mode);const sourceName='tradingstrategier-granskning.md';const source=view.sources.find((s:any)=>s.name===sourceName);if(source&&source.content!==content)throw Error(`${mode}: källfilen finns med annat innehåll; den bevaras.`);const missing=strategyFactoryCandidates.filter(c=>!view.strategies.some((s:any)=>s.baselineId===c.id));console.log(`${mode}: ${missing.length} nya forskningsposter, ${source?'källa finns':'ny källa'}`);if(!apply)continue;if(view.strategies.length+missing.length>50||!source&&view.sources.length>=50)throw Error('Biblioteket har nått sin gräns; befintligt innehåll bevaras.');const generation=view.connectionGeneration;
 const save=async(body:any)=>{if(view.connectionGeneration!==generation)throw Error('IG-kontot ändrades');const next=await api('/api/ig/research',{environment:mode,revision:view.revision,connectionGeneration:generation,...body});if(next.connectionGeneration!==generation)throw Error('IG-kontot ändrades under import');view=next;};
 if(!source)await save({action:'source',kind:'file',name:sourceName,content});const sourceId=view.sources.find((s:any)=>s.name===sourceName).id;
 for(const c of missing)await save({action:'strategy',name:c.name,baselineId:c.id,sourceIds:[sourceId],specification:JSON.stringify({status:'Forskningskandidat; ej körbar, ej IG-backtestad eller aktiverad',...c},null,2)});
 const check=await api(`/api/ig/research?environment=${mode}`);if(check.connectionGeneration!==generation||strategyFactoryCandidates.some(c=>!check.strategies.some((s:any)=>s.baselineId===c.id)))throw Error(`${mode}: importen kunde inte verifieras`);console.log(`${mode}: fem separata kandidater verifierade i gemensamt Strategy Library`);
}
if(!apply)console.log('Förhandskontroll klar; kör med --apply för additiv import. Ingen AI-analys, handel eller modellträning startas.');
