import assert from 'node:assert/strict';
import {createIgJevMarket,buildIgJevMarketRequest} from '../src/integrations/igJevMarket.js';
const now=Date.parse('2026-10-07T09:00:00Z');
const observation={epic:'CS.D.EURUSD.CFD.IP',timeframe:'1h',candles:[{close:1.1,closeTime:now-1000}],indicators:{rsi14:56,sma20:1.09,ema20:1.1,sma50:1.08},market:{quote:{observedAt:now-1000,marketStatus:'TRADEABLE',delayTime:0},account:{secret:'DO_NOT_SEND_ACCOUNT'}},account:{secret:'DO_NOT_SEND_ACCOUNT'},sourceText:'DO_NOT_SEND_SOURCE',strategyContext:{strategyId:'fixture',status:'evaluated',validationStatus:'notBacktested',entrySignal:true,entryConditions:{closeAboveEma12:true},rawText:'DO_NOT_SEND_SOURCE'}};
const request=buildIgJevMarketRequest([observation],now),serialized=JSON.stringify(request);
assert.ok(!serialized.includes('DO_NOT_SEND'));assert.ok(serialized.includes('rsi14'));assert.ok(serialized.includes('entrySignal'));assert.equal(Object.keys(request.questions).length,4);assert.equal(request.state.markets[0]?.forecastHorizon,'next_complete_bar');
const legacy=buildIgJevMarketRequest([{...observation,strategyComparisons:[{strategyId:'legacy',status:'blocked_missing_verified_volume',validationStatus:'notBacktested',indicators:{ema9:1.2,macd:0.2,sma200:NaN,private:'DO_NOT_SEND'},entryConditions:[{rule:{left:'ema9',op:'crosses_above',right:'ema20',factor:1,sourceText:'DO_NOT_SEND'},text:'DO_NOT_SEND',pass:true,left:1.2,right:1.1},{rule:{left:'DO_NOT_SEND',op:'DO_NOT_SEND',right:'DO_NOT_SEND'},pass:false,left:Infinity,right:NaN}],exitConditions:[{rule:{left:'rsi14',op:'>',right:55},pass:false,left:50,right:55}]}]}],now);
const projected=legacy.state.markets[0]!.strategyComparisons[0]!;assert.equal(projected.status,'blocked_missing_verified_volume');assert.equal(projected.indicators.ema9,1.2);assert.equal(projected.indicators.sma200,null);assert.ok(!JSON.stringify(legacy).includes('DO_NOT_SEND'));
assert.deepEqual(projected.entryConditions,[{pass:true,leftValue:1.2,rightValue:1.1,rule:{left:'ema9',op:'crosses_above',right:'ema20',factor:1}},{pass:false,leftValue:null,rightValue:null,rule:{left:null,op:null,right:null,factor:null}}]);assert.equal(projected.exitConditions?.[0]?.rule.right,55);
const answers={instrument_0_regime:{type:'choice',choice:'trending',confidence:0.7},instrument_0_direction:{type:'choice',choice:'up',confidence:0.6},instrument_0_strategy_fit:{type:'choice',choice:'aligned',confidence:0.8},instrument_0_missing_data:{type:'noul',noul:0.1}};
let calls=0;
const verdict={available:true,mode:'gateway',model:'typesafe-ai/jev',latencyMs:42,answers,note:''};
const service=createIgJevMarket({now:()=>now,ask:async(state,_timeout,questions)=>{calls++;assert.deepEqual(state,request.state);assert.deepEqual(questions,request.questions);return verdict as any;}});
const result=await service.assess([observation]);assert.equal(calls,1);assert.equal(result.available,true);assert.equal(result.route,'gateway');assert.equal(result.model,'typesafe-ai/jev');assert.equal(result.latencyMs,42);assert.equal(result.assessments[0]?.direction,'up');assert.equal(result.calibrated,false);assert.equal(result.canCreateSignal,false);assert.equal(result.canUpgradeSignal,false);
for(const change of [{instrument_0_direction:{type:'choice',choice:'BUY_NOW',confidence:1}},{instrument_0_direction:{type:'choice',choice:'up',confidence:NaN}},{instrument_0_missing_data:{type:'noul',noul:1.1}},{instrument_0_regime:undefined}]){
 const malformed=createIgJevMarket({now:()=>now,ask:async()=>({...verdict,answers:{...answers,...change}} as any)});const r=await malformed.assess([observation]);assert.equal(r.available,false);assert.equal(r.mode,'rules_only');assert.equal(r.assessments.length,0);assert.equal(r.route,'gateway');
}
const offline=createIgJevMarket({now:()=>now,ask:async()=>{throw Error('private provider error');}});assert.equal((await offline.assess([observation])).available,false);
assert.equal((await service.assess(Array(11).fill(observation))).available,false);assert.equal(calls,1,'Ogiltigt scope får aldrig anropa JEV');assert.equal((await service.assess([observation,observation])).available,false);
assert.equal(buildIgJevMarketRequest([{...observation,candles:[{close:1.1,closeTime:now+1}]}],now).state.markets[0]?.lastClosedBar.close,null);
let batchCalls=0;
const batch=createIgJevMarket({now:()=>now,ask:async(state,_timeout,questions)=>{batchCalls++;assert.equal((state.markets as any[]).length,10);assert.equal(Object.keys(questions!).length,40);const all:Record<string,any>={};for(let i=0;i<10;i++)for(const [key,value]of Object.entries(answers))all[key.replace('instrument_0_',`instrument_${i}_`)]=value;return {...verdict,answers:all,untrustedOrder:{side:'BUY'}} as any;}});
const many=await batch.assess(Array.from({length:10},(_,i)=>({...observation,epic:`EPIC${i}`})));assert.equal(batchCalls,1);assert.equal(many.assessments.length,10);assert.ok(!JSON.stringify(many).includes('untrustedOrder'));
console.log('IG JEV market: public derived context, en batch, typed judgments, route metadata, malformed fallback och no execution PASS');
