import assert from "node:assert/strict";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
const original = process.cwd();
const temp = mkdtempSync(path.join(tmpdir(), "paper-lots-"));
process.chdir(temp);
try {
  const { BybitPaperBroker } = await import("../src/brokers/bybitPaper.js");
  mkdirSync("data");
  writeFileSync("data/bybit-paper.json", JSON.stringify({usdc:8093,holdings:{ETH:{qty:1,avg:100,openedAt:1}},open:[],fills:[{id:"historik",base:"ETH",side:"BUY",qty:1,price:100,fee:0.1,at:1,kind:"MARKET"}]}));
  const broker = new BybitPaperBroker();
  assert.equal(broker.snapshot().usdc, 998093);
  assert.equal(broker.snapshot().holdings.ETH.qty, 1);
  assert.equal(broker.snapshot().fills.length, 1);
  assert.equal(new BybitPaperBroker().snapshot().usdc, 998093);

  // Injicera fasta priser: testet får aldrig nå nätverket.
  const mock = broker as unknown as { book: () => Promise<{bid: number; ask: number}> };
  mock.book = async () => ({ bid: 100, ask: 100 });
  const a = await broker.placeOrder({ symbol: "BTCUSDC", side: "BUY", type: "MARKET", quantity: 1 });
  const b = await broker.placeOrder({ symbol: "BTCUSDC", side: "BUY", type: "MARKET", quantity: 2 });
  await broker.cancelOrder("BTCUSDC", a.orderId);
  await broker.placeTimedExitOrder({ symbol: "BTCUSDC", side: "SELL", type: "MARKET", quantity: 2 }, b.orderId);
  assert.equal(await broker.getTimedExitQuantity("BTCUSDC", a.orderId), 1);
  assert.equal(await broker.getTimedExitQuantity("BTCUSDC", b.orderId), 0);
  await broker.placeOrder({ symbol: "BTCUSDC", side: "SELL", type: "MARKET", quantity: .5 });
  assert.equal(await broker.getTimedExitQuantity("BTCUSDC", a.orderId), .5);
  const restored = new BybitPaperBroker();
  assert.equal(await restored.getTimedExitQuantity("BTCUSDC", a.orderId), .5);
  assert.equal(await restored.getTimedExitQuantity("BTCUSDC", b.orderId), 0);
  assert.ok(broker.snapshot().feeRate > 0);
  let price = 100;
  mock.book = async () => ({ bid: price, ask: price });
  const low = await broker.placeOrder({ symbol: "SOLUSDC", side: "BUY", type: "MARKET", quantity: 1 });
  price = 200;
  const high = await broker.placeOrder({ symbol: "SOLUSDC", side: "BUY", type: "MARKET", quantity: 1 });
  price = 150;
  await broker.placeTimedExitOrder({ symbol: "SOLUSDC", side: "SELL", type: "MARKET", quantity: 1 }, low.orderId);
  const snap = broker.snapshot();
  const rate = snap.feeRate;
  const sold = snap.fills.find((f) => f.side === "SELL" && f.tradeId === low.orderId);
  assert.ok(sold && Math.abs((sold.pnl ?? 0) - (150 * (1 - rate) - 100 * (1 + rate))) < 1e-8, "Lotten använder sin egen ingångskostnad");
  assert.ok(Math.abs((snap.lots[high.orderId]?.costBasisRemaining ?? 0) - 200 * (1 + rate)) < 1e-8);
  assert.ok(Math.abs((snap.holdings.SOL?.avg ?? 0) - 200 * (1 + rate)) < 1e-8, "Kvarvarande innehavs snitt är lotten på 200");
  assert.equal(snap.fills.filter((f) => f.tradeId === low.orderId).length, 2);
  const beforeSaveFailure = broker.snapshot();
  mkdirSync("data/bybit-paper.json.tmp");
  await assert.rejects(broker.placeOrder({symbol:"XRPUSDC",side:"BUY",type:"MARKET",quantity:1}), /kunde inte sparas/);
  assert.deepEqual(broker.snapshot(),beforeSaveFailure,"Misslyckad persistens ändrar inte TEST-kontot");
  rmSync("data/bybit-paper.json.tmp",{recursive:true});
  const market = (broker as unknown as {market:{getTicker:(symbol:string)=>Promise<{symbol:string;price:number;changePct24h:number;volume24h:number}>}}).market;
  market.getTicker=async()=>{throw Error("Marknadspris offline");};
  await assert.rejects(broker.getAccount(),/offline/);
  await assert.rejects(broker.getPositions(),/offline/);
  const frozen = broker.snapshot();
  let release!: ()=>void;
  const quotesReady = new Promise<void>(resolve=>{release=resolve;});
  market.getTicker=async(symbol)=>{await quotesReady;return{symbol,price:150,changePct24h:0,volume24h:1};};
  const valuation = broker.getAccount();
  await broker.placeOrder({symbol:"XRPUSDC",side:"BUY",type:"MARKET",quantity:1});
  release();
  const coherent = await valuation;
  assert.equal(coherent.balances.find(b=>b.asset === "USDC")?.free,frozen.usdc,"Prisanrop blandar inte nytt kassasaldo med gamla innehav");
  const oldQty = Object.values(frozen.holdings).reduce((sum,h)=>sum+h.qty,0);
  assert.ok(Math.abs(coherent.totalValueUsdt - (frozen.usdc+oldQty*150)) < 1e-8);
  assert.equal(coherent.balances.some(b=>b.asset === "XRP"),false);
  console.log("PASS: separat lottförsäljning, manuell delstängning, omstart och avgiftssnapshot");
} finally { process.chdir(original); rmSync(temp, { recursive: true }); }
