import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createIgWorkspace} from '../src/integrations/igWorkspace.js';
import {createIgConnection} from '../src/integrations/igConnection.js';
import {createIgSchedules,stockholmSlot} from '../src/integrations/igSchedules.js';
import {createIgMarketDirectory,enrichIgDirectoryMarket} from '../src/integrations/igMarketDirectory.js';
let now=Date.parse('2026-10-07T07:00:00Z'),generation='one',starts=0;
const status=()=>({environments:{demo:{status:'connected',connectionGeneration:generation},live:{status:'disconnected'}}}) as any;
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'ig-schedule-test-'));
const deps={status,now:()=>now,directory,guard:async()=>true,start:async()=>{starts++;return {} as any;}};
const service=createIgSchedules(deps);
const input={name:'Morgon',epics:['CS.D.EURUSD.CFD.IP'],timeframe:'5m' as const,percent:1,horizonMinutes:15,durationMinutes:15,intervalMinutes:5,localTime:'09:00',weekdays:[3],enabled:true};
const schedule=service.save('demo',input);
await service.tick();await service.tick();assert.equal(starts,1,'Dubbletter startar inte igen');
now+=60000;await service.tick();assert.equal(starts,1);
generation='two';await service.tick();assert.equal(service.list('demo')[0]?.enabled,false,'Ny anslutning pausar');
service.enable('demo',schedule.id,true);assert.equal(createIgSchedules(deps).list('demo')[0]?.enabled,false,'Omstart kräver aktivering');
assert.equal(stockholmSlot(Date.parse('2026-10-25T00:30:00Z')).time,'02:30');assert.equal(stockholmSlot(Date.parse('2026-10-25T01:30:00Z')).time,'02:30');
assert.equal(enrichIgDirectoryMarket({bid:3,offer:2,percentageChange:-2}).spread,null);assert.equal(enrichIgDirectoryMarket({percentageChange:-2}).movementPercent,2);
let calls=0;
const catalog=createIgMarketDirectory({status,now:()=>now,budget:()=>({remaining:10,used:0}) as any,call:async()=>{calls++;throw Error('unsupported');},fallback:async()=>({markets:[{epic:'A',name:'EUR/USD',type:'CURRENCIES'}],note:'Delvis'}) as any});
const result=await catalog.catalogue('demo','forex');assert.equal(result.complete,false);assert.equal(result.markets.length,1);assert.equal(result.rankings.mostBought.available,false);await catalog.catalogue('demo','forex');assert.equal(calls,1);generation='three';await catalog.catalogue('demo','forex');assert.equal(calls,2,'Cache isoleras per kontoanslutning');
const official=createIgMarketDirectory({status,now:()=>now,budget:()=>({remaining:10,used:0}) as any,call:async(_mode,endpoint,_method,_version,_body,options)=>endpoint==='categories'?{categories:[{code:'CURRENCIES'}]}:{instruments:[{epic:'EUR',instrumentName:'EUR/USD',instrumentType:'CURRENCIES',bid:1,offer:1.1,percentageChange:2}],metadata:{pageNumber:0,pageSize:1000}},fallback:async()=>{throw Error('Fallback ska inte användas');}});
const all=await official.catalogue('demo','forex');assert.equal(all.complete,true);assert.equal(all.markets[0].changePercent,2);assert.equal(all.rankings.gainers.available,true);
now=Date.parse('2026-10-25T00:30:00Z');
service.save('demo',{...input,localTime:'02:30',weekdays:[7]});await service.tick();const afterFirst=starts;now=Date.parse('2026-10-25T01:30:00Z');await service.tick();assert.equal(starts,afterFirst,'DST-hösttimmen körs endast en gång');
const enriched=createIgMarketDirectory({status,now:()=>now,budget:()=>({remaining:10,used:0}) as any,call:async(_mode,endpoint)=>endpoint.startsWith('markets/')?{instrument:{epic:'EUR',marketId:'EURUSD'}}:{marketId:'EURUSD',longPositionPercentage:60,shortPositionPercentage:40},candles:async()=>({candles:Array.from({length:50},(_,i)=>({openTime:now-(50-i)*3600000,closeTime:now-(49-i)*3600000,close:100+i}))}) as any});
const metrics=await enriched.enrich('demo','EUR');assert.equal(metrics.sentimentLongPercent,60);assert.ok(metrics.trendScore!>0);
const emptyOfficial=createIgMarketDirectory({status,now:()=>now,budget:()=>({remaining:10,used:0}) as any,call:async(_mode,endpoint)=>endpoint==='categories'?{categories:[{code:'CURRENCIES'}]}:{instruments:[],metadata:{pageNumber:0,pageSize:1000}},fallback:async()=>({markets:[],note:'Sökreserv'}) as any});assert.equal((await emptyOfficial.catalogue('demo','forex')).complete,false);
const raceDirectory=fs.mkdtempSync(path.join(os.tmpdir(),'ig-race-test-'));let release!:()=>void;const blocked=new Promise<void>(r=>{release=r;});let raceStarts=0;
const race=createIgSchedules({...deps,directory:raceDirectory,start:async()=>{raceStarts++;await blocked;return {} as any;}});
now=Date.parse('2026-10-07T07:00:00Z');race.save('demo',input);const second=race.save('demo',{...input,name:'Andra'});const ticking=race.tick();await new Promise(r=>setImmediate(r));race.enable('demo',second.id,false);release();await ticking;assert.equal(raceStarts,1,'Pausat schema återstartas inte av stale snapshot');assert.equal(race.list('demo').find(x=>x.id===second.id)?.enabled,false);
now=Date.parse('2027-03-27T10:00:00Z');const spring=race.save('demo',{...input,recurrence:'once',date:'2027-03-28',localTime:'02:30'});now=Date.parse('2027-03-28T01:00:00Z');await race.tick();assert.equal(race.list('demo').find(x=>x.id===spring.id)?.enabled,false,'Vårhopp hoppas över och förfallet engångsschema pausas');
fs.rmSync(raceDirectory,{recursive:true,force:true});
const endpointCalls:string[]=[];const connection=createIgConnection({loadCredentials:()=>({demo:{apiKey:'fixture',identifier:'fixture',password:'fixture'}}),fetch:(async(url:string)=>{endpointCalls.push(url);return url.endsWith('/session')?new Response(JSON.stringify({currentAccountId:'account'}),{headers:{CST:'fixture','X-SECURITY-TOKEN':'fixture'}}):url.endsWith('/accounts')?new Response(JSON.stringify({accounts:[{accountId:'account',accountType:'CFD'}]})):new Response('{}');}) as typeof fetch});await connection.testConnection('demo');await connection.callAuthenticated('demo','categories');await connection.callAuthenticated('demo','categories/CURRENCIES/instruments','GET','1',undefined,{query:'pageNumber=0&pageSize=1000'});await connection.callAuthenticated('demo','client-sentiment/EURUSD');assert.ok(endpointCalls.some(x=>x.endsWith('/categories/CURRENCIES/instruments?pageNumber=0&pageSize=1000')));
const allowedCalls=endpointCalls.length;await assert.rejects(connection.callAuthenticated('demo','categories/CURRENCIES/instruments','GET','1',undefined,{query:'pageSize=1001'}));await assert.rejects(connection.callAuthenticated('demo','categories/CURRENCIES/instruments','GET','1',undefined,{query:'referenceEpic=private'}));await assert.rejects(connection.callAuthenticated('demo','client-sentiment/EURUSD','POST','1'));assert.equal(endpointCalls.length,allowedCalls,'Otillåtna kategorianrop blockeras före nätverket');
let sessionAllowed=true,finishMarket!:()=>void;let enteredMarket!:()=>void;const entered=new Promise<void>(r=>enteredMarket=r);const waitingMarket=new Promise<void>(r=>finishMarket=r);const cancelWorkspace=createIgWorkspace({status,now:()=>now,directory:path.join(directory,'cancel-start'),call:async(_mode,route)=>{enteredMarket();await waitingMarket;return {instrument:{epic:'EUR',type:'CURRENCIES'},snapshot:{},dealingRules:{}};}});
const pendingStart=cancelWorkspace.startSession('demo',{...input,epics:['EUR']},()=>sessionAllowed);await entered;sessionAllowed=false;finishMarket();await assert.rejects(pendingStart,/start avbruten/);assert.equal((await cancelWorkspace.workspace('demo')).session,null,'Paus under metadatahämtning skapar ingen session');
fs.rmSync(directory,{recursive:true,force:true});console.log('IG directory + schedules: alla kontroller godkända');
