import {mergeStreamCandle} from '/workspace/streamCandles.mjs';
import {frames,quoteIsFresh,scenario,sizeForCapitalRisk,increaseDraft,extendDeadline,normalizeSignal,marketMetric,rankMarkets} from '/workspace/model.mjs';
import {accountMarketActivity,accountMarketProfits,marketViewRows,marketTradeLabel,marketMetricLabel} from '/workspace/marketViews.mjs';
// Ett gemensamt tillstånd driver diagram, order, instrument, signaler och session.
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(v,d=2)=>Number.isFinite(v)?new Intl.NumberFormat('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v):'—';
const tradingColor=name=>getComputedStyle(document.documentElement).getPropertyValue(`--${name}`).trim();
const valueClass=v=>Number.isFinite(v)?v>0?'positive':v<0?'negative':'muted':'muted';
const signed=v=>Number.isFinite(v)?`${v>0?'+':''}${number(v)}`:'—';
const optionalNumber=v=>v==null||v===''?null:Number(v);
const time=t=>Number.isFinite(t)?new Date(t).toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'}):'—';
const duration=t=>t==null?'Ingen tidsplan':t<=0?'Tid ute · stängning inväntas':`${Math.floor(t/60000)}:${String(Math.floor(t/1000)%60).padStart(2,'0')}`;
const S={mode:'demo',simulation:false,category:'crypto',catalogView:'all',schedules:[],catalogState:{},searchStatus:'',catalogSearchStatus:'',catalog:[],selected:new Set(),current:null,market:null,candles:[],account:null,positions:[],pending:[],closed:[],signals:[],session:null,analysis:null,connection:null,chartFrame:'15m',analysisFrame:'5m',direction:'BUY',orderType:'MARKET',tradeTab:'open',favorites:new Set(),favoritesOnly:false,execution:{enabled:false,reason:'Serverns IG-ordergrind är inte verifierad'},generation:0,instrumentRevision:0,connecting:false,connectingGeneration:-1,connectError:null,selectionRevision:0,quoteState:'ready',lastCandleRefresh:0,historyPartial:false,history:null,positionsStatus:"unavailable",cost:null,review:null,maxPositions:1,preferencesRevision:0,streaming:null,analysisMemory:null};
try{S.favorites=new Set(JSON.parse(localStorage.getItem('trading-workspace-favorites')??'[]'));}catch{/* Felaktiga favoriter ignoreras. */}
let chart=null,candleSeries=null,lineSeries=null,smaSeries=null,priceLines=[],indicator=false,refreshing=false,searchTimer,toastTimer,selectionChain=Promise.resolve(),catalogChain=Promise.resolve();const catalogRequests=new Map();let catalogResumeAt=0,credentialsBusy=false,environmentStates={};
const localHost=['localhost','127.0.0.1','::1','[::1]'].includes(location.hostname);
const money=v=>`${number(v)} ${S.account?.currency??'—'}`;
const price=v=>number(v,S.market?.instrument?.decimalPlacesFactor??2);
const levelPrice=(epic,v)=>number(v,(S.current===epic?S.market:S.catalog.find(m=>m.epic===epic))?.instrument?.decimalPlacesFactor??5);
const nameOf=epic=>S.catalog.find(m=>m.epic===epic)?.name??S.positions.find(p=>p.epic===epic)?.instrumentName??epic;
const kind=m=>['crypto','forex'].includes(m.category)?m.category:m.type!=='CURRENCIES'?null:/bitcoin|ethereum|crypto|litecoin|ripple|solana|btc|eth\/|doge/i.test(m.name??'')?'crypto':'forex';
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function notice(message){$('notice').textContent=message;$('notice').classList.toggle('simulated',S.simulation);}
async function api(path,{method='GET',body}={}){
  if(S.simulation)throw Error('Designläge får inte anropa mäklar- eller agent-API');
  const r=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(path.includes('analysis')?150000:path.includes('catalog')?90000:30000),...(body?{body:JSON.stringify(body)}:{})});
  let data;try{data=await r.json();}catch{throw Error('Servern svarade inte med verifierbara data');}
  if(!r.ok||data.error||data.ok===false)throw Error(data.error??`Serverfel ${r.status}`);return data;
}
const ig=(path,params={})=>`/api/ig/${path}?${new URLSearchParams({environment:S.mode,...params})}`;
const selection=()=>({environment:S.mode,epics:[...S.selected],timeframe:S.analysisFrame,percent:Number($('session-percent').value),horizonMinutes:Number($('holding').value)});
function renderEnvironmentStatus(){
  const host=$('ig-environment-status');if(!host)return;
  host.innerHTML=['demo','live'].map(mode=>{const c=environmentStates[mode]??(mode===S.mode?S.connection:null),label=c?.status==='connected'?'Anslutet':c?.error??(c?.credentialsComplete?'Sparat · ej verifierat':'Uppgifter saknas');return `<div class="environment-status"><b>IG ${mode.toUpperCase()}</b><span class="${c?.status==='connected'?'positive':'amber'}">${esc(label)}${c?.account?` · ${esc(c.account.accountId)} · ${number(c.account.balance)} ${esc(c.account.currency)}`:''}</span><button type="button" data-account-mode="${mode}">Visa konto</button></div>`;}).join('');
}
function clearCredentialFields(){for(const id of ['ig-identifier','ig-password','ig-api-key'])$(id).value='';}
let socket=null,reconnectTimer=null,reconnectAttempt=0,realtimeEpoch=null,realtimeSequence=0,realtimeLastAt=0,realtimeSnapshot=false,subscriptionKey='',pingTimer=null,streamedAccount=null;
const streamScale=()=>['1m','3m','15m','30m'].includes(S.chartFrame)?'1MINUTE':S.chartFrame==='5m'?'5MINUTE':['1h','4h'].includes(S.chartFrame)?'HOUR':null;
const streamedBuckets=new Map();
const realtimeHealthy=()=>!S.simulation&&socket?.readyState===1&&realtimeSnapshot&&Date.now()-realtimeLastAt<45000;
function renderTransport(){const healthy=realtimeHealthy(),upstream=S.streaming?.status??'DISCONNECTED';$('transport-info').textContent=`${healthy?'WebSocket synkad':'REST-reserv · återansluter WebSocket'} · IG ${upstream} · diagram ${streamScale()?'streaming när tillgänglig':'REST 60 s'} · katalog/historik REST${S.streamingLimit?' · '+S.streamingLimit:''}`;$('footer-source').textContent=S.simulation?'DEMODATA · inga externa anrop':`IG ${S.mode.toUpperCase()} · ${healthy?'WebSocket synkad':'REST-reserv'}`;}
function stopRealtime(){streamedBuckets.clear();streamedAccount=null;clearTimeout(reconnectTimer);clearInterval(pingTimer);if(socket){const old=socket;socket=null;old.close();}realtimeSnapshot=false;realtimeLastAt=0;realtimeEpoch=null;realtimeSequence=0;subscriptionKey='';}
function subscribeRealtime(){if(S.simulation||socket?.readyState!==1)return;const wanted=[...new Set([S.current,...S.positions.map(p=>p.epic),...S.selected,...S.favorites].filter(Boolean))];S.streamingLimit=wanted.length>30?`${wanted.length} önskade · 30 streamas; positioner och urval prioriteras`:null;const epics=wanted.slice(0,30),scale=streamScale(),chart=S.current&&scale?{epic:S.current,scale}:null,key=JSON.stringify({epics,chart});if(key===subscriptionKey)return;subscriptionKey=key;socket.send(JSON.stringify({type:'subscribe',epics,chart}));}
function connectRealtime(){
  if(S.simulation||typeof WebSocket==='undefined'||socket)return;const generation=S.generation,mode=S.mode,own=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/ig/realtime?environment=${mode}`);socket=own;
  own.onopen=()=>{if(socket!==own)return;reconnectAttempt=0;subscriptionKey='';subscribeRealtime();clearInterval(pingTimer);pingTimer=setInterval(()=>{if(socket===own&&own.readyState===1)own.send(JSON.stringify({type:'ping',at:Date.now()}));if(realtimeLastAt&&Date.now()-realtimeLastAt>45000)own.close();},15000);};
  own.onmessage=safe(async event=>{if(socket!==own||generation!==S.generation||mode!==S.mode||S.simulation)return;const m=JSON.parse(event.data);if(m.environment!==mode||!Number.isInteger(m.sequence))return;if(m.epoch!==realtimeEpoch){realtimeEpoch=m.epoch;realtimeSequence=0;realtimeSnapshot=false;}if(m.sequence<=realtimeSequence)return;realtimeSequence=m.sequence;realtimeLastAt=Date.now();const data=m.data??{};
    if(m.type==='snapshot'){realtimeSnapshot=true;await refresh(data);subscribeRealtime();}
    if(m.type==='quote'){if(data.generation&&S.connection?.connectionGeneration&&data.generation!==S.connection.connectionGeneration)return;const old=S.catalog.find(x=>x.epic===data.epic);if(old?.quote?.observedAt>data.observedAt)return;if(old)Object.assign(old,{bid:data.bid,offer:data.offer,changePercent:data.changePercent,quote:data});if(S.current===data.epic&&S.market&&!(S.market.quote?.observedAt>data.observedAt))S.market={...S.market,quote:data};renderInstruments();if($('catalog-dialog').open)renderCatalog();for(const p of S.positions)if(p.epic===data.epic){p.bid=data.bid;p.offer=data.offer;}renderTrades();renderChart();recalculate();}
    if(m.type==='candle'&&data.epic===S.current&&data.scale===streamScale()){
      if(data.generation&&S.connection?.connectionGeneration&&data.generation!==S.connection.connectionGeneration)return;
      const seconds=frames[S.chartFrame],sourceSeconds=data.scale==='HOUR'?3600:data.scale==='5MINUTE'?300:60,bucket=Math.floor(data.openTime/(seconds*1000))*seconds*1000,key=`${S.current}:${S.chartFrame}`,prior=S.candles.find(x=>x.openTime===bucket);
      if(!streamedBuckets.has(key))streamedBuckets.set(key,new Map());
      const parts=streamedBuckets.get(key),merged=mergeStreamCandle(prior,data,seconds,sourceSeconds,parts);
      for(const oldBucket of parts.keys())if(oldBucket<bucket-seconds*1000*2)parts.delete(oldBucket);
      S.candles=[...S.candles.filter(x=>x.openTime!==bucket),merged].sort((a,b)=>a.openTime-b.openTime).slice(-500);S.lastCandleRefresh=Date.now();renderChart();
      if(seconds!==sourceSeconds&&data.closed&&data.openTime+sourceSeconds*1000>=bucket+seconds*1000&&!merged.closed){await chooseInstrument(S.current,{reset:false});}
    }
    if(m.type==='account'){if(data.generation&&S.connection?.connectionGeneration&&data.generation!==S.connection.connectionGeneration)return;streamedAccount=data;S.account={...S.account,...Object.fromEntries(Object.entries(data).filter(([,value])=>value!==null))};renderHeader();recalculate();}
    if(m.type==='stream-status'){S.streaming=data;renderTransport();}
    if(m.type==='subscription-error'){subscriptionKey='';toast(data.message);notice(data.message);}
    if(m.type==='sync-error'){realtimeSnapshot=false;S.execution={enabled:false,reason:data.message};if(S.market?.quote)S.market.quote.receivedAt=0;recalculate();notice(data.message);}
    renderTransport();
  });
  own.onerror=()=>own.close();own.onclose=()=>{if(socket!==own)return;socket=null;realtimeSnapshot=false;S.lastCandleRefresh=0;subscriptionKey='';clearInterval(pingTimer);renderTransport();if(generation===S.generation&&!S.simulation)reconnectTimer=setTimeout(connectRealtime,Math.min(30000,1000*2**reconnectAttempt++)+Math.random()*500);};
}
function renderHeader(){
  renderEnvironmentStatus();
  $('ig-platform-signals').href=S.mode==='demo'?'https://demo-deal.ig.com/web-platform/#/workspace/NmFjNjJhMmVkN2U0MDkwNmU2NjZmMDdh':'https://deal.ig.com/web-platform/#/workspace/NmFjNTg1OTRhYjM1MWEwNzE1ODEyZTc1';
  for(const id of ['ig-identifier','ig-password','ig-api-key','ig-credentials-environment','ig-credentials-submit'])$(id).disabled=!localHost||S.simulation||credentialsBusy;
  const a=S.account;$('currency').textContent=a?.currency??'—';$('balance').textContent=number(a?.balance);$('available').textContent=number(a?.available);$('pnl').textContent=signed(a?.profitLoss);$('pnl').className=valueClass(a?.profitLoss);
  document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===S.mode));
  const connected=S.connection?.status==='connected'&&S.quoteState!=='disconnected';$('connection').textContent=S.simulation?'● DEMODATA':connected?`● IG ${S.mode==='demo'?'Demo':'Live'}`:'○ Ej ansluten';$('connection').classList.toggle('positive',connected&&!S.simulation);$('connect').disabled=S.simulation||S.connecting;$('connect').textContent=S.connecting?'Ansluter IG…':connected?'Verifiera IG':'Anslut IG';
  $('order-environment').textContent=S.simulation?'DEMODATA':`IG ${S.mode.toUpperCase()}`;
  $('source-label').textContent=S.simulation?'DESIGNLÄGE · lokala simulerade data':`IG CFD · ${S.mode==='demo'?'Demo':'Live'} · ${realtimeHealthy()?'WebSocket':'REST-reserv'}`;
  $('footer-source').textContent=S.simulation?'DEMODATA · inga mäklar- eller AI-anrop':`IG ${S.mode==='demo'?'Demo':'Live'} · separat konto och tillstånd`;
  $('footer-cost').textContent=S.simulation?'AI-kostnad: 0 · simulerat':S.cost?`AI idag: $${number(S.cost.today?.totalUsd??S.cost.dailyUsd??S.cost.todayUsd)} · befintlig budgetgräns`:'AI-kostnad: —';
  $('execution-status').textContent=S.simulation?'Lokal simulering · inga verkliga order':`${S.execution.reason??'IG-ordergrind ej verifierad'}${S.account?.currency&&!['USD','SEK'].includes(S.account.currency)?' · Kontovalutan '+S.account.currency+' stöds inte för nya order.':''}`;
}
function visibleMarkets(){const q=$('search').value.trim().toLowerCase();return S.catalog.filter(m=>kind(m)===S.category&&(!S.favoritesOnly||S.favorites.has(m.epic))&&(!q||`${m.name} ${m.epic}`.toLowerCase().includes(q)));}
function instrumentRow(m){return `<div class="instrument-row ${S.current===m.epic?'current':''}"><input type="checkbox" data-select="${esc(m.epic)}" aria-label="Analysera ${esc(m.name)}" ${S.selected.has(m.epic)?'checked':''}><button data-chart="${esc(m.epic)}"><span class="symbol">${esc(m.name)}</span><span class="quote">${number(m.bid,m.instrument?.decimalPlacesFactor??(kind(m)==='forex'?5:2))} ${S.simulation?'· demo':''}</span></button><button class="star ${S.favorites.has(m.epic)?'favorite':''}" data-star="${esc(m.epic)}" aria-label="Favorit ${esc(m.name)}">${S.favorites.has(m.epic)?'★':'☆'}</button></div>`;}
function renderInstruments(){
  document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===S.category));
  const markets=visibleMarkets();$('instrument-count').textContent=markets.length;
  const status=S.catalogState[S.category]?.status;const note=!S.simulation&&status&&status!=='ready'?`<p class="field-note">${esc(catalogMessage(S.category))}</p>`:'';
  $('instruments').innerHTML=(S.searchStatus?`<p class="field-note">${esc(S.searchStatus)}</p>`:'')+note+(markets.length?markets.map(instrumentRow).join(''):`<div class="empty-state"><b>Inga instrument</b>${esc(catalogMessage(S.category))} Öppna katalogen för att ladda om.</div>`);
  $('favorites-toggle').classList.toggle('positive',S.favoritesOnly);renderSelection();
}
function renderSelection(){
  renderMarketsPage();
  subscribeRealtime();
  $('selection-list').textContent=S.selected.size?[...S.selected].map(nameOf).join(' · '):'Inga instrument valda';
  $('analyze').disabled=!S.selected.size||S.analysis?.status==='running'||S.quoteState==='disconnected';
  $('selection-status').textContent=`${S.selected.size} valda · ${S.analysisFrame} analys · ${S.simulation?'demodata':'delat serverurval'}`;
  $('session-selection').textContent=`${S.simulation?'DEMODATA':`IG ${S.mode.toUpperCase()}`} · ${[...S.selected].map(nameOf).join(', ')||'Välj instrument i vänsterpanelen'}`;
  $('session-frame').value=S.analysisFrame;
}
async function syncSelection(){
  renderSelection();if(S.simulation)return;
  const revision=++S.selectionRevision,generation=S.generation,payload=selection();
  selectionChain=selectionChain.catch(()=>{}).then(async()=>{
    if(generation!==S.generation||revision!==S.selectionRevision)return;
    try{await api('/api/ig/selection',{method:'POST',body:payload});if(generation===S.generation&&revision===S.selectionRevision){S.selectionSavedAt=Date.now();$('selection-status').textContent=`${payload.epics.length} valda · synkat med agentsessionen`;} }
    catch(e){if(generation===S.generation){$('selection-status').textContent=`Urval ej sparat: ${e.message}`;throw e;}}
  });
  await selectionChain;
}
function mergeMarkets(markets){const entries=new Map(S.catalog.map(m=>[m.epic,m]));for(const m of markets){const old=entries.get(m.epic);const preserve=old?.quote?.observedAt>(m.quote?.observedAt??0);entries.set(m.epic,{...old,...m,...(preserve?{quote:old.quote,bid:old.quote.bid,offer:old.quote.offer,changePercent:old.changePercent}:{}),category:m.category??old?.category});}S.catalog=[...entries.values()];}
const marketStatusLabel=m=>({TRADEABLE:'Öppen',CLOSED:'Stängd',OFFLINE:'Offline',EDITS_ONLY:'Endast ändringar',SUSPENDED:'Pausad',ON_AUCTION:'Auktion',ON_AUCTION_NO_EDITS:'Auktion'})[m.marketStatus??m.quote?.marketStatus]??'Status ej verifierad';
function marketActivity(){return accountMarketActivity(S.catalog,{positions:S.positions,positionsStatus:S.positionsStatus,history:S.history});}
function renderMarketsPage(){
  if($('markets-page').hidden)return;
  const activity=marketActivity(),profits=accountMarketProfits(S.catalog,{history:S.history,currency:S.account?.currency});
  const rows=marketViewRows(S.catalog.map(m=>({...m,percentageChange:m.quote?.changePercent??m.percentageChange,sentiment:m.sentiment??(Number.isFinite(m.sentimentLongPercent)?{longPositionPercentage:m.sentimentLongPercent}:null),accountProfit:profits.get(m.epic)})),{query:$('markets-search').value,sort:$('markets-sort').value,favorites:S.favorites,kind,activity}).filter(m=>$('markets-scope').value==='selected'?S.selected.has(m.epic):$('markets-scope').value==='favorites'?S.favorites.has(m.epic):true);
  $('markets-page-status').textContent=`${catalogMessage('all')} · ${activity.note}`;
  $('markets-selected-count').textContent=`${S.selected.size} / 10 valda`;
  $('markets-analyze').disabled=!S.selected.size||S.analysis?.status==='running'||(!S.simulation&&S.connection?.status!=='connected');
  $('markets-session-open').disabled=!S.selected.size;
  for(const category of ['forex','crypto']){
    const group=rows.filter(m=>m.category===category);$('markets-'+category+'-count').textContent=`${group.length} instrument`;
    $('markets-'+category+'-list').innerHTML=group.length?group.map(m=>`<article class="market-card ${S.selected.has(m.epic)?'selected':''}"><div class="market-card-title"><label><input type="checkbox" data-select="${esc(m.epic)}" aria-label="Analysera ${esc(m.name)}" ${S.selected.has(m.epic)?'checked':''}><b>${esc(m.name)}</b></label><small>${esc(marketStatusLabel(m))}</small></div><div class="market-card-metrics"><span>Dagens riktning<b>${esc(marketMetricLabel(m,'trend'))}</b></span><span>Kontots affärer<b>${esc(marketTradeLabel(m))}</b></span><span>Kontots resultat<b>${esc(marketMetricLabel(m,'profit'))}</b></span><span>IG-köpintresse<b>${esc(marketMetricLabel(m,'buying'))}</b></span></div><div class="market-card-actions"><button class="star ${S.favorites.has(m.epic)?'favorite':''}" data-star="${esc(m.epic)}" aria-label="Favorit ${esc(m.name)}">${S.favorites.has(m.epic)?'★':'☆'}</button><button data-chart="${esc(m.epic)}">Visa diagram</button></div></article>`).join(''):'<p class="market-empty">Inga instrument matchar urvalet.</p>';
  }
}
function showTradingView(){ $('markets-page').hidden=true;document.querySelector('.workspace').hidden=false;document.querySelector('.mobile-tabs').hidden=false;$('trading-view').classList.add('active');$('markets-open').classList.remove('active');chart?.resize($('chart').clientWidth,$('chart').clientHeight); }
$('trading-view').onclick=showTradingView;
$('markets-open').onclick=safe(async()=>{document.querySelector('.workspace').hidden=true;document.querySelector('.mobile-tabs').hidden=true;$('markets-page').hidden=false;$('trading-view').classList.remove('active');$('markets-open').classList.add('active');renderMarketsPage();const generation=S.generation;await loadCatalog('forex');if(generation===S.generation)await loadCatalog('crypto');renderMarketsPage();});
$('markets-search').oninput=renderMarketsPage;$('markets-scope').onchange=renderMarketsPage;$('markets-sort').onchange=renderMarketsPage;
$('markets-reload').onclick=safe(async()=>{const generation=S.generation;await loadCatalog('forex',{force:true});if(generation===S.generation)await loadCatalog('crypto',{force:true});renderMarketsPage();});
$('markets-analyze').onclick=safe(analyze);$('markets-session-open').onclick=()=>{renderSelection();$('session-dialog').showModal();};
function catalogRows(){const q=$('catalog-search').value.trim().toLowerCase();return rankMarkets(S.catalog.filter(m=>['forex','crypto'].includes(kind(m))&&(S.catalogView==='all'||(S.catalogView==='favorites'?S.favorites.has(m.epic):kind(m)===S.catalogView))&&($('market-status').value==='all'||(m.marketStatus??m.quote?.marketStatus)===$('market-status').value)&&(!q||`${m.name} ${m.epic}`.toLowerCase().includes(q))),$('market-ranking').value);}
function catalogMessage(view=S.catalogView){
  if(S.simulation)return 'DESIGNLÄGE · lokal instrumentlista';
  const states=['favorites','all'].includes(view)?['forex','crypto'].map(c=>S.catalogState[c]??{}):[S.catalogState[view]??{}];
  if(states.some(s=>s.status==='loading'))return 'Hämtar IG-katalogen…';
  const error=states.find(s=>s.status==='error');if(error)return `Katalogen kunde inte hämtas: ${error.error}. Ladda om för att försöka igen.`;
  if(states.some(s=>s.status==='partial'||s.complete===false))return `Alla hämtade IG-instrument · listan kan vara ofullständig.${states.some(s=>s.remainingSearches>0)?' Fler instrument hämtas tidigast om en minut; Ladda om kan återuppta hämtningen.':' Sök ytterligare par hos IG eller ladda om.'}`;
  if(states.some(s=>!s.status))return 'Anslut IG för att hämta kontots instrument.';
  return `Hela kategorin hämtad · ${catalogRows().length} instrument i sökresultatet`;
}
function renderCatalog(){
  const rows=catalogRows();document.querySelectorAll('[data-catalog-category]').forEach(b=>b.classList.toggle('active',b.dataset.catalogCategory===S.catalogView));
  $('catalog-status').textContent=catalogMessage();$('catalog-discovery').textContent=S.catalogSearchStatus;$('catalog-reload').disabled=S.simulation||Object.values(S.catalogState).some(s=>s.status==='loading');
  const ranking=$('market-ranking').value;
  $('market-ranking-note').textContent=({name:'IG-katalog för valt konto. Saknade uppgifter visas som saknas.',up:'IG:s procentförändring för leverantörens jämförelseperiod. Inte realiserad vinst.',down:'IG:s procentförändring för leverantörens jämförelseperiod.',movement:'Absolut procentförändring. Stor rörelse innebär inte högre vinstchans.',spread:'Bid/ask-spread i procent av mittkurs. Olika kontrakt kan ha olika kostnader.',sentiment:'Andel IG-kunder med longposition när verifierad sentimentdata finns. Inte handelsvolym.',trendUp:'Trend kräver historik från stängda candles. Saknade trendvärden rankas sist.',trendDown:'Trend kräver historik från stängda candles. Saknade trendvärden rankas sist.'})[ranking];
  const metricLabel={name:'Förändring',up:'Förändring',down:'Förändring',movement:'Rörelse',spread:'Spread %',sentiment:'Long %',trendUp:'Trend',trendDown:'Trend'}[ranking];
  const row=m=>{const value=marketMetric(m,ranking==='name'?'up':ranking);return `<div class="catalog-row"><input type="checkbox" data-select="${esc(m.epic)}" aria-label="Analysera ${esc(m.name)}" ${S.selected.has(m.epic)?'checked':''}><div class="catalog-name">${esc(m.name)}<small>${esc(m.epic)} · ${esc(marketStatusLabel(m))}</small></div><div class="market-price">${number(m.quote?.bid??m.bid,kind(m)==='forex'?5:2)}<small>Bid</small></div><div class="market-metric">${value===null?'Saknas':number(ranking==='movement'?Math.abs(value):value)}<small>${metricLabel}</small></div><button class="star ${S.favorites.has(m.epic)?'favorite':''}" data-star="${esc(m.epic)}" aria-label="Favorit ${esc(m.name)}">${S.favorites.has(m.epic)?'★':'☆'}</button><button data-chart="${esc(m.epic)}">Visa diagram</button></div>`;};
  $('catalog-content').innerHTML=rows.length?['forex','crypto'].map(category=>{const group=rows.filter(m=>kind(m)===category);return group.length?`<section class="market-group"><h3>${category==='forex'?'Forex':'Kryptovalutor'} <span>${group.length} instrument</span></h3>${group.map(row).join('')}</section>`:'';}).join(''):`<p class="catalog-empty">Inga instrument matchar filtren. ${esc(catalogMessage())}</p>`;
  for(const id of ['catalog-session','catalog-schedule','market-enrich'])$(id).disabled=!S.selected.size;
  $('catalog-selection-count').textContent=`${S.selected.size} / 10 valda för analys`;$('catalog-analyze').disabled=!S.selected.size||S.analysis?.status==='running'||S.quoteState==='disconnected'||(!S.simulation&&S.connection?.status!=='connected');$('catalog-select-results').disabled=!rows.length;
}
async function loadCatalog(category,{force=false}={}){
  if(S.simulation){renderCatalog();return;}
  const generation=S.generation,mode=S.mode,key=`${generation}:${mode}:${category}`;
  if(catalogRequests.has(key))return catalogRequests.get(key);
  if(!force&&S.catalogState[category]?.status==='ready'&&S.catalogState[category]?.complete)return;
  if(S.connection?.status!=='connected'){S.catalogState[category]={status:'error',error:'IG är inte anslutet'};renderCatalog();return;}
  catalogResumeAt=Date.now();S.catalogState[category]={...S.catalogState[category],status:'loading'};renderCatalog();renderInstruments();
  const job=catalogChain.catch(()=>{}).then(async()=>{
    if(generation!==S.generation)return;
    try{
      const result=await api(ig('directory',{category}));if(generation!==S.generation)return;
      const found=(result.markets??[]).filter(m=>kind(m)===category);
      mergeMarkets(found);if(result.complete===true){const epics=new Set(found.map(m=>m.epic));S.catalog=S.catalog.filter(m=>kind(m)!==category||epics.has(m.epic));}S.catalogState[category]={status:result.status==='ready'&&result.complete===true?'ready':'partial',complete:result.complete===true,error:result.error,updatedAt:result.updatedAt,remainingSearches:result.remainingSearches};
    }catch(e){if(generation===S.generation)S.catalogState[category]={status:'error',complete:false,error:e.message};}
    finally{if(generation===S.generation){renderInstruments();renderCatalog();}}
  });catalogChain=job;catalogRequests.set(key,job);try{await job;}finally{catalogRequests.delete(key);}
}
async function loadCatalogView(force=false){const generation=S.generation;if(['favorites','all'].includes(S.catalogView)){await loadCatalog('forex',{force});if(generation!==S.generation)return;await loadCatalog('crypto',{force});}else await loadCatalog(S.catalogView,{force});}
async function discoverTerm(term,source){
  const input=$(source==='catalog'?'catalog-search':'search'),category=source==='catalog'?S.catalogView:S.category,statusKey=source==='catalog'?'catalogSearchStatus':'searchStatus';
  if(S.simulation||['favorites','all'].includes(category)||term.trim().length<2||S.connection?.status!=='connected'||(source==='catalog'?catalogRows():visibleMarkets()).length)return;
  const generation=S.generation;S[statusKey]='Söker ytterligare instrument hos IG…';renderInstruments();renderCatalog();
  const job=catalogChain.catch(()=>{}).then(async()=>{
    if(generation!==S.generation||input.value!==term||category!==(source==='catalog'?S.catalogView:S.category))return;
    try{const result=await api(ig('markets',{searchTerm:term.trim()}));if(generation!==S.generation||input.value!==term||category!==(source==='catalog'?S.catalogView:S.category))return;
      const matches=(result.markets??[]).filter(m=>['all','popular'].includes(category)?['forex','crypto'].includes(kind(m)):kind(m)===category);mergeMarkets(matches);S[statusKey]=matches.length?`${matches.length} ytterligare instrument hämtade från IG`:'IG returnerade inga ytterligare instrument i kategorin.';
    }catch(e){if(generation===S.generation&&input.value===term)S[statusKey]=`IG-sökning misslyckades: ${e.message}. Ändra sökningen för att försöka igen.`;}
    finally{if(generation===S.generation){renderInstruments();renderCatalog();}}
  });catalogChain=job;await job;
}
async function changeCategory(category){S.instrumentRevision++;S.category=category;S.catalogView=category;$('search').value='';$('catalog-search').value='';S.searchStatus='';S.catalogSearchStatus='';renderInstruments();renderCatalog();await loadCatalog(category);}

function initializeChart(){
  if(!window.LightweightCharts)return;
  chart=window.LightweightCharts.createChart($('chart'),{layout:{background:{color:'#000000'},textColor:'#8493a8',fontFamily:'Inter, sans-serif',fontSize:10},grid:{vertLines:{color:'#1b2432'},horzLines:{color:'#1b2432'}},rightPriceScale:{borderColor:'#253143'},timeScale:{borderColor:'#253143',timeVisible:true,secondsVisible:false},crosshair:{mode:0},handleScroll:true,handleScale:true});
  candleSeries=chart.addCandlestickSeries({upColor:tradingColor('green'),downColor:tradingColor('red'),borderVisible:false,wickUpColor:tradingColor('green'),wickDownColor:tradingColor('red')});
  lineSeries=chart.addLineSeries({color:tradingColor('green'),lineWidth:2,visible:false});smaSeries=chart.addLineSeries({color:'#dbb674',lineWidth:1,priceLineVisible:false,lastValueVisible:false,visible:false});
  new ResizeObserver(entries=>{for(const e of entries)if(e.contentRect.width>0&&e.contentRect.height>0)chart.resize(e.contentRect.width,e.contentRect.height);}).observe($('chart'));
}
function renderChart(fit=false){
  if(!chart)initializeChart();
  const m=S.market;$('instrument-name').textContent=m?.name??'Välj instrument';$('order-symbol').textContent=m?.name??'Välj instrument';$('market-kind').textContent=`${kind(m??{})==='forex'?'FOREX':'KRYPTO'} · ${S.simulation?'DEMODATA':'IG CFD'}`;$('epic-label').textContent=m?.epic??'Samma handelsyta för krypto och forex';
  $('bid').textContent=price(m?.quote?.bid);$('ask').textContent=price(m?.quote?.offer);$('unit').textContent=m?.instrument?.unit??'kontrakt';
  $('chart-empty').hidden=!!S.candles.length;
  $('chart-source').textContent=S.simulation?'Demodata · simulerade mid-ljus':S.candles.length?`${realtimeHealthy()&&S.streaming?.status==='CONNECTED:WS-STREAMING'&&Date.now()-(S.candles.at(-1)?.receivedAt??0)<60000?'IG WebSocket · live mid-ljus':'IG historiska mid-ljus'}${S.candles.at(-1)?.partial?' · pågående ljus: delvis underlag':''}`:'Inga IG-ljus';
  $('chart-freshness').textContent=!m?'—':quoteIsFresh(m)?`${m.quote.source?.includes('WebSocket')?'IG WebSocket':'IG-kvot'} · prisålder ${Math.max(0,Math.floor((Date.now()-m.quote.observedAt)/1000))} s · mottagen ${time(m.quote.receivedAt)}`:'Inaktuell / ej verifierad kvot';$('chart-freshness').className=m&&!quoteIsFresh(m)?'amber':'';
  if(chart){
    const candles=S.candles.map(c=>({time:Math.floor(c.openTime/1000),open:c.open,high:c.high,low:c.low,close:c.close})).sort((a,b)=>a.time-b.time).filter((c,i,a)=>!i||c.time!==a[i-1].time);
    const autoScale=original=>{const info=original();if(!info)return info;const levels=S.positions.filter(p=>p.epic===S.current).flatMap(p=>[p.level,p.stopLevel,p.limitLevel]).filter(v=>Number.isFinite(v)&&v>0);if(levels.length){info.priceRange.minValue=Math.min(info.priceRange.minValue,...levels);info.priceRange.maxValue=Math.max(info.priceRange.maxValue,...levels);}return info;};
    const precision=Number.isInteger(m?.instrument?.decimalPlacesFactor)&&m.instrument.decimalPlacesFactor>=0&&m.instrument.decimalPlacesFactor<=8?m.instrument.decimalPlacesFactor:2;
    const priceFormat={type:'price',precision,minMove:10**(-precision)};
    candleSeries.applyOptions({autoscaleInfoProvider:autoScale,priceFormat});lineSeries.applyOptions({autoscaleInfoProvider:autoScale,priceFormat,color:tradingColor((candles.at(-1)?.close??0)>=(candles.at(-2)?.close??candles.at(-1)?.open??0)?'green':'red')});smaSeries.applyOptions({priceFormat});
    candleSeries.setData(candles);lineSeries.setData(candles.map((c,i)=>({time:c.time,value:c.close,color:tradingColor(c.close>=(candles[i-1]?.close??c.open)?'green':'red')})));
    const sma=[];for(let i=19;i<candles.length;i++)sma.push({time:candles[i].time,value:candles.slice(i-19,i+1).reduce((s,c)=>s+c.close,0)/20});smaSeries.setData(sma);
    const line=$('chart-type').value==='line';candleSeries.applyOptions({visible:!line});lineSeries.applyOptions({visible:line});smaSeries.applyOptions({visible:indicator});
    for(const p of priceLines)p.series.removePriceLine(p.line);priceLines=[];
    const series=line?lineSeries:candleSeries;
    const add=(level,title,color)=>{if(Number.isFinite(level)&&level>0)priceLines.push({series,line:series.createPriceLine({price:level,color,lineWidth:1,lineStyle:2,axisLabelVisible:true,title})});};
    for(const p of S.positions.filter(p=>p.epic===S.current)){add(p.level,`${p.direction==='BUY'?'Long':'Short'} · ingång`,tradingColor(p.direction==='BUY'?'green':'red'));add(p.stopLevel,'SL',tradingColor('red'));add(p.limitLevel,'TP',tradingColor('green'));}
    if(fit)chart.timeScale().fitContent();
  }
  recalculate();
}
// IG:s CFD-punktvärde kan inte härledas säkert från bara spotkursen.
function instrumentRules(){
  const i=S.market?.instrument;
  if(S.simulation)return {pointValue:i?.pointValue,pointCurrency:S.account?.currency,marginRate:i?.marginRate,minSize:i?.minSize,step:i?.step};
  // Servern får bara exponera explicit verifierade beräkningsregler.
  return S.market?.calculationRules??{pointValue:null,pointCurrency:null,marginRate:null};
}
function ticket(){const rules=instrumentRules();return {direction:S.direction,entry:S.orderType==='LIMIT'?Number($('limit').value):S.direction==='BUY'?S.market?.quote?.offer:S.market?.quote?.bid,stop:Number($('stop').value),target:Number($('target').value),size:Number($('size').value),...rules,available:S.account?.available,currency:S.account?.currency};}
function recalculate(){
  document.querySelectorAll('[data-direction]').forEach(b=>b.classList.toggle('active',b.dataset.direction===S.direction));document.querySelectorAll('[data-order-type]').forEach(b=>b.classList.toggle('active',b.dataset.orderType===S.orderType));$('limit-field').hidden=S.orderType!=='LIMIT';const unsupportedClose=!S.simulation&&S.orderType==='LIMIT';$('auto-close').disabled=unsupportedClose;$('auto-close').title=unsupportedClose?'IG limitorder stängs manuellt tills fyllnad kan avstämmas entydigt':'';if(unsupportedClose)$('auto-close').checked=false;
  const t=ticket(),calc=scenario(t);$('risk').textContent=calc.risk==null?'Okänd':money(-calc.risk);$('reward').textContent=calc.reward==null?'Okänd':money(calc.reward);$('reward-percent').textContent=calc.percent==null?'—':`${number(calc.percent)} %`;$('exposure').textContent=calc.exposure==null?'Okänd':money(calc.exposure);$('margin').textContent=calc.margin==null?'Okänd':money(calc.margin);$('spread').textContent=S.market?price(S.market.quote?.offer-S.market.quote?.bid):'—';
  $('scenario-note').textContent=calc.valid?`${instrumentRules().marginBasis??'Brutto före avgifter/slippage'} · R:R ${number(calc.ratio,1)} · risk ${number(calc.capitalPercent)} % av tillgängligt kapital.`:calc.error;
  $('review-order').disabled=!S.market||!quoteIsFresh(S.market)||!calc.valid;
  $('order-warning').textContent=S.market&&!quoteIsFresh(S.market)?'Order blockerad: marknaden eller prisernas färskhet kan inte verifieras.':'En kopierad signal är ett orderutkast. Granska innan du bekräftar.';
}
function signalCard(s){
  const action=s.action==='BUY'?'Köp / Long':s.action==='SELL'?'Sälj / Short':'Avvakta',color=s.action==='BUY'?'positive':s.action==='SELL'?'negative':'muted';
  const copyable=s.copyable&&Date.now()<s.validUntil&&S.quoteState==='ready';
  const market=S.catalog.find(m=>m.epic===s.epic),rules=S.simulation?{pointValue:market?.pointValue,pointCurrency:S.account?.currency}:market?.calculationRules??{};
  const projected=scenario({direction:s.action,entry:s.entryLevel,stop:s.stopLevel,target:s.targetLevel,size:1,...rules,currency:S.account?.currency,available:S.account?.available});
  const projectedHtml=s.action==='HOLD'?'':projected.valid?`<div class="row"><span class="muted">Brutto / 1 kontrakt</span><span><b class="positive">+${number(projected.reward)}</b> / <b class="negative">−${number(projected.risk)}</b> ${esc(S.account?.currency)}</span></div>`:'<small>Beloppsscenario inväntar verifierade kontraktsregler.</small>';
  return `<article class="signal-card"><div class="row"><button class="card-symbol" data-chart="${esc(s.epic)}">${esc(nameOf(s.epic))}</button><b class="${color}">${action}</b></div>${S.simulation?'<span class="sim-label">DEMODATA · SIMULERAD SIGNAL</span>':''}<p class="signal-reason">${esc(s.reason??'Ingen motivering')}</p><div class="row muted"><span>${esc(s.timeframe)} analys · ${time(s.completedAt)}</span><span>◷ ${s.horizonMinutes} min</span></div>${s.action!=='HOLD'?`<div class="signal-levels"><span><small>INGÅNG</small><b>${levelPrice(s.epic,s.entryLevel)}</b></span><span><small>STOP-LOSS</small><b class="negative">${levelPrice(s.epic,s.stopLevel)}</b></span><span><small>MÅLPRIS</small><b class="positive">${levelPrice(s.epic,s.targetLevel)}</b></span></div>`:''}${projectedHtml}<div class="row muted"><span>Giltig till ${time(s.validUntil)}</span><span>${Date.now()>=s.validUntil?'Utgången':''}</span></div><button class="copy-signal" data-copy="${esc(s.epic)}" ${copyable?'':'disabled'}>${s.action==='HOLD'?'Avvakta · inget orderförslag':'Kopiera signal'}</button></article>`;
}
function renderSignals(){
  $('signal-count').textContent=S.signals.length;$('analysis-status').textContent=S.analysis?.status==='running'?'◌ Analys pågår':S.analysis?.status==='failed'?'Analys misslyckades':S.analysis?.status==='completed'?`Analys klar ${time(S.analysis.completedAt)}`:'Inväntar analys';
  $('signals').innerHTML=S.signals.length?S.signals.map(signalCard).join(''):`<div class="empty-state"><b>${S.analysis?.status==='running'?'Agenterna arbetar…':'Inga agentsignaler'}</b>${S.analysis?.error?esc(S.analysis.error):'Välj instrument och starta analys. Avvakta är ett beslut.'}</div>`;
}
function positionPnl(p){
  if(S.simulation){const m=S.catalog.find(m=>m.epic===p.epic),exit=p.direction==='BUY'?m?.bid:m?.offer;const pnl=(p.direction==='BUY'?1:-1)*(exit-p.level)*p.size*(m?.pointValue??1);return {current:exit,pnl,percent:pnl/(p.level*p.size*(m?.pointValue??1))*100};}
  return {current:p.direction==='BUY'?p.bid:p.offer,pnl:p.profitLoss??null,percent:p.profitLossPercent??null};
}
function tradeCard(p){const calc=positionPnl(p);return `<article class="trade-card"><div class="row"><button class="card-symbol" data-chart="${esc(p.epic)}">${esc(p.instrumentName??nameOf(p.epic))}</button><span class="${p.direction==='BUY'?'positive':'negative'}">${p.direction==='BUY'?'Köp / Long':'Sälj / Short'}</span></div>${S.simulation?'<span class="sim-label">DEMODATA · SIMULERAD POSITION</span>':''}<div class="row"><b class="pnl-value ${valueClass(calc.pnl)}">${calc.pnl==null?'P/L ej verifierad':`${signed(calc.pnl)} ${esc(p.pnlCurrency??p.currency??S.account?.currency)}`}</b><span>${calc.percent==null?'—':`${signed(calc.percent)} % av exponering`}</span></div><div class="row muted"><span>${number(p.size)} kontrakt</span><span>◷ ${duration(p.closeAt? p.closeAt-Date.now():null)}</span></div><div class="row"><span class="muted">Ingång → aktuell</span><span>${levelPrice(p.epic,p.level)} → ${levelPrice(p.epic,calc.current)}</span></div><div class="row"><span class="negative">SL ${levelPrice(p.epic,p.stopLevel)}</span><span class="positive">TP ${levelPrice(p.epic,p.limitLevel)}</span></div><details><summary>Visa mer</summary><div class="row"><span>Öppnad</span><b>${p.openedAt?time(p.openedAt):'Tid ej verifierad'}</b></div><div class="row"><span>Position</span><b>${esc(p.dealId)}</b></div><small>Brutto-P/L · vinstprocent av exponering. Avgifter kan vara okända.</small></details><div class="card-actions"><button data-double="${esc(p.dealId)}">Double up</button><button data-roll="${esc(p.dealId)}">Roll over</button><button class="close-position" data-close-position="${esc(p.dealId)}" ${p.closing||p.closeStatus==='confirmed'?'disabled':''}>${p.closeStatus==='confirmed'?'IG bekräftade stängning':p.closing?'Stängning pågår':'Stäng'}</button></div>${p.closeError?`<span class="negative">Stängning misslyckades: ${esc(p.closeError)}</span>`:''}</article>`;}
function renderTrades(){
  document.querySelectorAll('[data-trades]').forEach(b=>b.classList.toggle('active',b.dataset.trades===S.tradeTab));$('history-filters').hidden=S.tradeTab!=='closed';$('trade-count').textContent=S.positions.length;
  if(S.tradeTab==='open'){$('trades').innerHTML=S.positions.length?S.positions.map(tradeCard).join(''):'<div class="empty-state"><b>Inga öppna positioner</b>Bekräftade IG-positioner visas här.</div>';return;}
  if(S.tradeTab==='pending'){$('trades').innerHTML=S.pending.length?S.pending.map(p=>`<article class="trade-card"><div class="row"><button class="card-symbol" data-chart="${esc(p.epic)}">${esc(nameOf(p.epic))}</button><span class="badge">${esc(p.status==='accepted'?'Accepterad · väntar på fyllnad':p.status==='failed'||p.status==='rejected'?'Orderfel':p.status==='unknown'?'Okänt IG-utfall':p.status==='submitted'?'Skickad · väntar på IG':'Väntande')}</span></div>${S.simulation?'<span class="sim-label">DEMODATA · SIMULERAD ORDER</span>':''}<p>${p.direction==='BUY'?'Köp / Long':'Sälj / Short'} · ${p.size==null?'storlek ej verifierad':`${number(p.size)} kontrakt`}</p><small>${esc(p.previousConnection?'Tidigare kontosession · kräver avstämning':p.error??p.blocker??p.reason??'Inväntar fyllnad')}</small>${S.simulation&&p.status==='pending'?`<div class="card-actions"><button data-fill="${esc(p.id)}">Simulera fyllnad</button><button data-cancel="${esc(p.id)}">Avbryt</button></div>`:''}</article>`).join(''):'<div class="empty-state"><b>Inga väntande order</b>En signal är inte en accepterad order eller en öppen position.</div>';return;}
  const days=Number($('period-filter').value),rows=S.closed.filter(t=>($('trade-filter').value!=='current'||t.epic===S.current)&&(!t.closedAt||Date.now()-t.closedAt<=days*86400000));
  $('trades').innerHTML=(S.historyPartial?'<p class="field-note">Ofullständig IG-historik · endast hämtad sida visas.</p>':'')+(rows.length?rows.map(t=>`<article class="trade-card"><div class="row">${t.epic?`<button class="card-symbol" data-chart="${esc(t.epic)}">${esc(t.instrumentName??nameOf(t.epic))}</button>`:`<b>${esc(t.instrumentName??'IG-transaktion')}</b>`}<b class="${valueClass(t.pnl)}">${Number.isFinite(t.pnl)?signed(t.pnl):esc(t.profitAndLoss??'Okänd')} ${esc(t.currency??'')}</b></div>${S.simulation?'<span class="sim-label">DEMODATA · SIMULERAD AFFÄR</span>':''}<div class="row muted"><span>Ingång → utgång</span><span>${number(t.entry??optionalNumber(t.openLevel))} → ${number(t.exit??optionalNumber(t.closeLevel))}</span></div><div class="row"><span>Öppnad ${time(t.openedAt)}</span><span>Stängd ${time(t.closedAt)}</span></div><small>Orsak: ${esc(t.reason??'Ej verifierad av IG')} · kostnader ${t.costs==null?'okända':`${number(t.costs)} ${esc(t.currency)}`}</small></article>`).join(''):'<div class="empty-state"><b>Inga verifierade avslut</b>Kontohändelser och insättningar räknas inte som avslutade trades.</div>');
}
function renderSession(){
  if($('settings-dialog').open)renderStrategyEvidence();
  const session=S.session,running=session?.status==='running';$('session-status').textContent=running?'● Aktiv':session?.status==='completed'?'Avslutad':session?.status==='stopped'?'Stoppad':session?.status==='interrupted'?'Avbruten':'Vilande';$('session-status').classList.toggle('positive',running);$('session-stop').hidden=!running;
  $('session-timing').textContent=running?`${duration(session.endsAt-Date.now())} kvar · senaste ${time(S.analysis?.completedAt)} · nästa ${time(session.nextRunAt)}`:session?.lastError??'Analys, innehavstid och sessionslängd är separata.';
  const a=S.analysis,steps=a?.steps??[];
  if(a?.status==='completed'&&a.jev?.available===false)steps[0]={status:'Otillgänglig · tidigare routing'};
  $('agent-steps').innerHTML=[['JEV','Förkontroll'],['Teknisk analytiker','Stängda ljus'],['Hanna / Head Trader','Beslut']].map(([name,caption],i)=>`${i?'<i>→</i>':''}<span>0${i+1} <b>${name}</b><small>${esc(steps[i]?.status??(a?.status==='completed'?'Klar':a?.status==='running'&&i===0?'Arbetar':'Inväntar analys'))} · ${caption}</small></span>`).join('');
}
function renderAll(){if($('import-signal-dialog').open)renderImportedSignals();if($('catalog-dialog').open)renderCatalog();renderHeader();renderInstruments();renderTrades();renderSignals();renderSession();renderChart();}
function clearAccountState(){S.analysisMemory=null;importedSignals=[];if($('import-signal-dialog').open)$('import-signal-dialog').close();stopRealtime();S.schedules=[];S.preferencesRevision=0;S.streaming=null;S.favorites=new Set();S.catalog=[];S.catalogState={};S.searchStatus='';S.catalogSearchStatus='';S.catalogView=S.category;$('catalog-search').value='';S.selected=new Set();S.current=null;S.market=null;S.candles=[];S.positions=[];S.pending=[];S.closed=[];S.history=null;S.positionsStatus="unavailable";S.signals=[];S.analysis=null;S.session=null;S.account=null;S.connection=null;S.connecting=false;S.connectingGeneration=-1;S.connectError=null;S.execution={enabled:false,reason:'IG-ordergrind ej verifierad'};$('stop').value='';$('target').value='';S.generation++;S.selectionRevision++;}
async function switchMode(mode){
  const sameMode=mode===S.mode;
  if(sameMode&&(S.simulation||S.connection?.status==='connected'||S.connecting&&S.connectingGeneration===S.generation))return;
  if(!sameMode){S.mode=mode;clearAccountState();$('search').value='';}
  if(S.simulation){loadSimulation();return;}
  const generation=S.generation;connectRealtime();renderAll();notice(`IG ${mode==='demo'?'Demo':'Live'} valt. Kontot och priserna verifieras separat.`);
  const status=await api('/api/ig/status');if(generation!==S.generation)return;
  environmentStates=status.environments??{};S.connection=environmentStates[mode];renderHeader();
  if(S.connection?.status==='connected'){await refresh();if(generation===S.generation)await restoreChart();}
  else if(S.connection?.configured&&S.connection?.credentialsComplete)await connect();
  else{await refresh();if(generation===S.generation)notice(S.connection?.error??'IG-uppgifterna behöver kompletteras i Inställningar.');}
}

async function restoreChart(){
  const generation=S.generation;let revision=S.instrumentRevision;
  let saved;try{saved=JSON.parse(localStorage.getItem(`trading-chart-${S.mode}`)??'null');}catch{/* Ett ogiltigt sparat diagram ignoreras. */}
  if(saved?.epic&&/^[A-Za-z0-9._-]{1,100}$/.test(saved.epic)){await chooseInstrument(saved.epic);if(generation!==S.generation)return;revision=S.instrumentRevision;}
  await loadCatalog(S.category);
  if(generation!==S.generation||revision!==S.instrumentRevision||S.current&&S.market)return;
  const first=S.catalog.find(m=>m.epic===saved?.epic)??S.catalog.find(m=>kind(m)===S.category&&(m.marketStatus??m.quote?.marketStatus)==='TRADEABLE');
  if(first)await chooseInstrument(first.epic);
}
async function startWorkspace(){
  connectRealtime();
  try{const status=await api('/api/ig/status');environmentStates=status.environments??{};S.connection=environmentStates[S.mode];
    if(S.connection?.status==='connected'){await refresh();await restoreChart();}
    else if(S.connection?.status==='configured'&&S.connection?.credentialsComplete)await connect();
    else await refresh();
  }catch(e){notice(`IG kunde inte återställas: ${e.message}`);}
}


async function chooseInstrument(epic,{reset=true}={}){
  const generation=S.generation;S.instrumentRevision++;S.current=epic;subscribeRealtime();S.market=null;S.candles=[];if(reset){$('stop').value='';$('target').value='';$('limit').value='';}renderInstruments();renderChart();
  if(S.simulation){const item=S.catalog.find(m=>m.epic===epic);if(!item)return;S.category=kind(item);S.market=simulationMarket(item);S.candles=simulationCandles(item);renderInstruments();renderChart(true);return;}
  try{const frame=S.chartFrame;const [m,c]=await Promise.all([api(ig('market',{epic})),api(ig('candles',{epic,timeframe:frame,limit:100}))]);if(generation!==S.generation||S.current!==epic||S.chartFrame!==frame)return;S.market={...m,category:m.category??S.catalog.find(x=>x.epic===epic)?.category};S.candles=c.candles??[];S.lastCandleRefresh=Date.now();try{localStorage.setItem(`trading-chart-${S.mode}`,JSON.stringify({epic}));}catch{/* Diagrammet fungerar även utan lokal lagring. */}S.category=kind(S.market)??S.category;if(!S.catalog.some(x=>x.epic===epic))S.catalog.push({...S.market,bid:m.quote?.bid,offer:m.quote?.offer});renderInstruments();renderChart(true);}catch(e){if(generation===S.generation&&S.current===epic){S.market=null;S.candles=[];renderChart();toast(e.message);}}
}
async function copySignal(epic){const s=S.signals.find(s=>s.epic===epic);if(!s||!s.copyable||Date.now()>=s.validUntil){toast('Signalen är Avvakta, ofullständig eller utgången.');return;}await chooseInstrument(epic);if(!S.market||!quoteIsFresh(S.market)){toast('Signalen kopierades inte: verifierad färsk kvot saknas.');return;}S.direction=s.action;S.orderType='MARKET';$('limit').value=s.entryLevel;$('stop').value=s.stopLevel;$('target').value=s.targetLevel;$('holding').value=s.horizonMinutes;recalculate();toast('Signal kopierad till orderutkast. Ingen order skickad.');}
async function refresh(snapshot=null){
  if(S.simulation||refreshing)return;refreshing=true;const generation=S.generation;
  try{const w=snapshot??await api(ig('workspace'));if(generation!==S.generation)return;
    if(Object.prototype.hasOwnProperty.call(w,'analysisMemory'))S.analysisMemory=w.analysisMemory;if(w.importedSignals)importedSignals=w.importedSignals;if(w.preferences){S.favorites=new Set(w.preferences.favorites??[]);S.preferencesRevision=w.preferences.revision??0;}if(w.schedules){S.schedules=w.schedules;if($('schedules-dialog').open)renderSchedules();}if(w.streaming)S.streaming=w.streaming;
    S.connection=w.connection;environmentStates[S.mode]=w.connection;S.history=w.history;S.positionsStatus=w.positionsStatus??"unavailable";S.account=w.connection?.account;const accountAt=w.checkedAt??w.connection?.checkedAt??0;if(streamedAccount&&streamedAccount.generation===w.connection?.connectionGeneration&&streamedAccount.receivedAt>accountAt&&Date.now()-streamedAccount.receivedAt<60000)S.account={...S.account,...Object.fromEntries(Object.entries(streamedAccount).filter(([,value])=>value!==null))};S.positions=w.positions??[];S.pending=w.pendingOrders??[];if(w.pendingOrderStatus==='unavailable'&&w.connection?.status==='connected')S.pending.push({status:'unknown',error:'IG:s väntande order kunde inte hämtas. Listan kan vara ofullständig.'});S.closed=(w.history?.transactions??[]).filter(t=>t.cashTransaction===false&&t.type==='DEAL').map(t=>({...t,closedAt:Date.parse(t.date?.replace(/\//g,'-')??''),epic:(w.history?.activities??[]).find(a=>a.dealId===t.reference)?.epic}));
    S.historyPartial=w.history?.complete===false;S.analysis=w.analysis;S.signals=w.analysis?.status==='completed'?(w.analysis?.head?.analyses??[]).map(s=>normalizeSignal(s,w.analysis)):[];S.session=w.session;S.execution=w.execution??S.execution;
    // Ett osparat lokalt urval skrivs aldrig över av en äldre polling-request.
    if(!S.selectionRevision||(snapshot&&Date.now()-(S.selectionSavedAt??0)>2000)){S.selected=new Set(w.selection?.epics??[]);S.analysisFrame=w.selection?.timeframe??S.analysisFrame;$('analysis-frame').value=S.analysisFrame;}
    mergeMarkets((w.markets??[]).filter(m=>m.name).map(m=>({...m,bid:m.quote?.bid,offer:m.quote?.offer})));
    renderHeader();
    if(S.current){const epic=S.current,m=w.markets?.find(m=>m.epic===epic)??(snapshot?S.market:await api(ig('market',{epic})));if(generation!==S.generation)return;if(epic===S.current&&m){const quote=S.market?.quote&&S.market.quote.observedAt>(m.quote?.observedAt??0)?S.market.quote:m.quote;S.market={...m,quote,category:m.category??S.catalog.find(x=>x.epic===epic)?.category};}}
    $('connection-details').textContent=S.connection?.error??`IG ${S.mode.toUpperCase()} · ${S.connection?.status??'ej ansluten'} · konto ${S.account?.accountId??'—'}`;renderTransport();
    if(S.current&&Date.now()-S.lastCandleRefresh>=60000&&(S.lastCandleRefresh===0||!realtimeHealthy()||!streamScale())){
      const epic=S.current,frame=S.chartFrame,c=await api(ig('candles',{epic,timeframe:frame,limit:100}));
      if(generation!==S.generation)return;
      if(epic===S.current&&frame===S.chartFrame){S.candles=c.candles??[];S.lastCandleRefresh=Date.now();}
    }
    renderAll();if(S.connectError)notice(S.connectError);else if(S.analysis?.status==='failed')notice(S.analysis.error??'Analys misslyckades');else notice(S.connection?.status==='connected'?`IG ${S.mode.toUpperCase()} ansluten · ${S.candles.length} ljus · ${realtimeHealthy()?'WebSocket':'REST-reserv'}`:S.connection?.error??'Anslut IG för att visa kontot och priserna.');
  }catch(e){if(generation===S.generation){S.execution={enabled:false,reason:`IG-data kunde inte uppdateras: ${e.message}`};if(S.market?.quote)S.market={...S.market,quote:{...S.market.quote,receivedAt:0,observedAt:0}};renderAll();notice(`IG-data kunde inte hämtas: ${e.message}`);}}
  finally{refreshing=false;}
}
async function connect(){
  if(S.simulation||S.connecting&&S.connectingGeneration===S.generation)return;
  const generation=S.generation,mode=S.mode,revision=S.instrumentRevision,category=S.category;
  S.connecting=true;S.connectingGeneration=generation;S.connectError=null;renderHeader();notice(`Ansluter IG ${mode.toUpperCase()} · verifierar konto och priser…`);
  try{
    const result=await api('/api/ig/connect',{method:'POST',body:{environment:mode}});
    if(generation!==S.generation)return;
    environmentStates=result.environments??environmentStates;const status=result.environments?.[mode];if(status?.status!=='connected')throw Error(status?.error??'IG-anslutningen saknar verifierat konto');
    await refresh();if(generation!==S.generation)return;
    await loadCatalog(category);if(generation!==S.generation)return;
    // Anslutningen får inte ersätta ett instrument som användaren väljer under väntan.
    if(!S.current&&revision===S.instrumentRevision&&category===S.category){
      await restoreChart();
    }
    if(generation!==S.generation)return;
    if(S.connection?.status!=='connected')throw Error(S.connection?.error??'Kontodata kunde inte verifieras efter anslutning');
    notice(`IG ${mode.toUpperCase()} ansluten. ${S.market?'Diagrammet visar valt instrument.':'Inget tillgängligt instrument hittades; sök i vänsterpanelen.'} Priser läses via REST; orderstatus visas separat.`);
  }catch(e){if(generation===S.generation){S.connectError=`IG ${mode.toUpperCase()} kunde inte anslutas: ${e.message}`;notice(S.connectError);throw e;}}
  finally{if(S.connectingGeneration===generation){S.connecting=false;renderHeader();}}
}
async function analyze(){if(!S.selected.size)throw Error('Välj minst ett instrument');if(S.simulation){simulateAnalysis();return;}await syncSelection();const generation=S.generation;S.analysis={status:'running',steps:[{status:'Arbetar'}]};renderSignals();renderSession();renderSelection();try{const a=await api('/api/ig/analysis',{method:'POST',body:selection()});if(generation!==S.generation)return;S.analysis=a;await refresh();toast('Analysen är klar. Läs agentsignalerna bredvid diagrammet.');}catch(e){if(generation===S.generation){S.analysis={status:'failed',error:e.message};renderSignals();throw e;}}finally{renderSelection();}}
function openReview(title,html,callback,enabled=true){S.review=callback;$('review-title').textContent=title;$('review-content').innerHTML=html;$('confirm-order').disabled=!enabled;$('confirm-order').textContent=S.simulation?'Bekräfta simulering':'Bekräfta';$('review-dialog').showModal();}
async function reviewOrder(){const t=ticket(),calc=scenario(t);if(!calc.valid||!quoteIsFresh(S.market))throw Error('Orderunderlag eller färsk kvot saknas');const order={epic:S.current,direction:S.direction,size:t.size,entry:t.entry,stopLevel:t.stop,targetLevel:t.target,orderType:S.orderType,holdingMinutes:Number($('holding').value),autoClose:$('auto-close').checked};
  let serverDraft=null;
  if(!S.simulation){serverDraft=await api('/api/ig/order-preview',{method:'POST',body:{environment:S.mode,...order}});t.entry=serverDraft.entry;order.entry=serverDraft.entry;calc.risk=serverDraft.risk;calc.exposure=serverDraft.exposure;calc.margin=serverDraft.margin;calc.reward=serverDraft.reward??Math.abs(t.target-t.entry)*calc.risk/Math.abs(t.entry-t.stop);}
  const generation=S.generation;
  openReview('Granska order',`<div class="selected-summary">${S.simulation?'DEMODATA · lokal simulering':`IG ${S.mode.toUpperCase()}`} · ${esc(nameOf(order.epic))}</div><div class="review-lines"><div class="row"><span>Riktning / storlek</span><b>${order.direction==='BUY'?'Köp':'Sälj'} · ${number(order.size)} kontrakt</b></div><div class="row"><span>Ingång / SL / TP</span><b>${price(t.entry)} / ${price(t.stop)} / ${price(t.target)}</b></div><div class="row"><span>Risk / potentiell vinst</span><b>${money(calc.risk)} / ${money(calc.reward)}</b></div><div class="row"><span>Innehavstid</span><b>${order.holdingMinutes} minuter</b></div></div><p class="field-note">${S.simulation?'Ingen verklig order. Limitordrar väntar på simulerad fyllnad.':esc(S.execution.reason)}</p>`,async()=>{
    if(generation!==S.generation)throw Error('Kontot ändrades; granska ett nytt orderunderlag');
    if(!S.simulation){const result=await api('/api/ig/order-confirm',{method:'POST',body:{environment:S.mode,draftId:serverDraft.id}});await refresh();toast(result.status==='accepted'?'IG accepterade ordern · inväntar positionssynk':result.error??'IG inväntar orderbekräftelse');return;}
    if(S.quoteState==='order-error'){toast('Orderfel: simulerad mäklaravvisning. Ingen position öppnad.');S.pending.push({...order,id:crypto.randomUUID(),status:'failed',blocker:'Simulerad orderavvisning'});renderTrades();return;}
    if(S.positions.length>=S.maxPositions)throw Error('Gränsen för samtidiga positioner är nådd');
    if(order.orderType==='LIMIT'){S.pending.push({...order,id:crypto.randomUUID(),status:'pending'});S.tradeTab='pending';}else addSimulationPosition(order);renderTrades();renderChart();toast('Simulerad order accepterad.');
  },S.simulation||S.execution.enabled);
}
function addSimulationPosition(order){S.positions.push({dealId:crypto.randomUUID(),epic:order.epic,instrumentName:nameOf(order.epic),direction:order.direction,size:order.size,level:order.entry,stopLevel:order.stopLevel,limitLevel:order.targetLevel,currency:S.account.currency,openedAt:Date.now(),closeAt:order.autoClose?Date.now()+order.holdingMinutes*60000:null});S.tradeTab='open';}
async function doubleUp(id){const p=S.positions.find(p=>p.dealId===id),draft=increaseDraft(p);await chooseInstrument(draft.epic);S.direction=draft.direction;$('size').value=draft.size;$('stop').value=draft.stop??'';$('target').value=draft.target??'';S.orderType='MARKET';recalculate();toast(`Double up: ny order för ${number(draft.size)} kontrakt. Total storlek blir ${number(draft.size*2)}; risk och marginal ökar. Granska ordern.`);}
function rollOver(id){const generation=S.generation,binding=S.connection?.connectionGeneration;const p=S.positions.find(p=>p.dealId===id);if(!p)throw Error('Positionen saknas');const minutes=Number($('holding').value),next=extendDeadline(p,minutes);openReview('Roll over · förläng innehavstid',`<div class="selected-summary">${esc(nameOf(p.epic))} · ${S.simulation?'DEMODATA':`IG ${S.mode.toUpperCase()}`}</div><div class="review-lines"><div class="row"><span>Ny planerad tid</span><b>${time(next)} (+${minutes} min)</b></div></div><p class="field-note">Detta ändrar en planerad stängningsbegäran. CFD-kontraktet har ingen fast utgångstid. Storlek, stop-loss och målpris ändras inte. ${S.simulation?'':'Servern måste ha en verifierad tidsstängning för positionen.'}</p>`,async()=>{if(generation!==S.generation)throw Error('Kontot ändrades; granska igen');if(!S.simulation){await api('/api/ig/rollover',{method:'POST',body:{environment:S.mode,dealId:p.dealId,minutes,connectionGeneration:binding}});await refresh();toast('IG-positionens planerade tidsstängning förlängd');return;}p.closeAt=next;renderTrades();toast('Simulerad innehavstid förlängd.');},S.simulation||S.execution.enabled);}
function closePosition(id){const generation=S.generation,binding=S.connection?.connectionGeneration;const p=S.positions.find(p=>p.dealId===id);if(!p)throw Error('Positionen saknas');openReview('Stäng position',`<div class="selected-summary">${esc(nameOf(p.epic))} · ${number(p.size)} kontrakt</div><p class="field-note">${S.simulation?'DEMODATA: simulerat avslut till aktuell kvot.':'Stängning kräver serverns verifierade IG-orderfunktion. En begäran är inte ett bekräftat avslut.'}</p>`,async()=>{
  if(generation!==S.generation)throw Error('Kontot ändrades; granska igen');if(!S.simulation){const result=await api('/api/ig/close',{method:'POST',body:{environment:S.mode,dealId:p.dealId,connectionGeneration:binding}});await refresh();toast(result.status==='confirmed'?'IG bekräftade stängningen':result.error??'Stängning begärd · inväntar IG-bekräftelse');return;}p.closing=true;renderTrades();await new Promise(r=>setTimeout(r,450));p.closing=false;
  if(S.quoteState==='order-error'||S.quoteState==='disconnected'||S.quoteState==='stale'){p.closeError='Simulerad avvisning eller prisfel';renderTrades();return;}
  const calc=positionPnl(p);S.closed.unshift({...p,entry:p.level,exit:calc.current,pnl:calc.pnl,costs:null,closedAt:Date.now(),reason:'Manuell stängning'});S.positions=S.positions.filter(x=>x.dealId!==id);renderTrades();renderChart();toast('Stängning bekräftad · simulering');
},S.simulation||S.execution.enabled);}
// Demodata finns enbart i ett uttryckligen aktiverat designläge.
const DEMO=[{epic:'DEMO.BTC.USD',name:'Bitcoin / USD',type:'CURRENCIES',bid:62840,offer:62864,pointValue:1},{epic:'DEMO.ETH.USD',name:'Ethereum / USD',type:'CURRENCIES',bid:2452.1,offer:2454.6,pointValue:1},{epic:'DEMO.SOL.USD',name:'Solana / USD',type:'CURRENCIES',bid:148.24,offer:148.5,pointValue:1},{epic:'DEMO.EUR.USD',name:'EUR / USD',type:'CURRENCIES',bid:10942.6,offer:10943.4,pointValue:1},{epic:'DEMO.GBP.USD',name:'GBP / USD',type:'CURRENCIES',bid:13108.1,offer:13109.4,pointValue:1},{epic:'DEMO.USD.JPY',name:'USD / JPY',type:'CURRENCIES',bid:14862.4,offer:14863.5,pointValue:1}];
function simulationMarket(m){return {...m,status:'ready',quote:{bid:m.bid,offer:m.offer,receivedAt:S.quoteState==='stale'?Date.now()-120000:Date.now(),marketStatus:S.quoteState==='disconnected'?'OFFLINE':'TRADEABLE',delayTime:0,source:'DEMODATA'},instrument:{unit:'demokontrakt · USD / punkt',pointValue:m.pointValue,marginRate:0.2,minSize:0.01,step:0.01,decimalPlacesFactor:2}};}
function simulationCandles(m){const now=Math.floor(Date.now()/(frames[S.chartFrame]*1000))*frames[S.chartFrame]*1000,vol=m.bid*.001;let previous=m.bid-vol*3;return Array.from({length:100},(_,i)=>{const open=previous,close=m.bid+Math.sin(i*.19)*vol*3+Math.sin(i*.71)*vol*.8+(i-99)*vol*.025;previous=close;return {openTime:now-(100-i)*frames[S.chartFrame]*1000,open,close,high:Math.max(open,close)+vol*.5,low:Math.min(open,close)-vol*.4};});}
function simulationSignals(){const at=Date.now(),analysis={completedAt:at,selection:{timeframe:S.analysisFrame,horizonMinutes:15}};return [...S.selected].map((epic,i)=>{const m=S.catalog.find(m=>m.epic===epic),action=i===2?'HOLD':i%2?'SELL':'BUY',entry=action==='BUY'?m.offer:m.bid,distance=m.bid*.006;return normalizeSignal({epic,action,reason:action==='HOLD'?'Avvakta: svag trend och motstridiga momentumvärden.':'Simulerad agentanalys: tydlig trend och återtest av stödnivå. Bekräfta signalen före order.',entryLevel:action==='HOLD'?null:entry,stopLevel:action==='HOLD'?null:entry+(action==='BUY'?-1:1)*distance,targetLevel:action==='HOLD'?null:entry+(action==='BUY'?1:-1)*distance*2},analysis);});}
function loadSimulation(){S.maxPositions=3;S.catalog=DEMO.map(m=>({...m}));S.account={balance:25000,available:21450,profitLoss:86.4,currency:'USD'};S.connection={status:'connected'};S.execution={enabled:true,reason:'Enbart lokal simulering'};S.selected=new Set(['DEMO.BTC.USD','DEMO.ETH.USD','DEMO.EUR.USD']);S.current=S.category==='forex'?'DEMO.EUR.USD':'DEMO.BTC.USD';S.market=simulationMarket(S.catalog.find(m=>m.epic===S.current));S.candles=simulationCandles(S.market);S.signals=simulationSignals();S.analysis={status:'completed',completedAt:Date.now(),steps:[{status:'Klar'},{status:'Klar'},{status:'Klar'}]};S.positions=[{dealId:'demo-btc',epic:'DEMO.BTC.USD',instrumentName:'Bitcoin / USD',direction:'BUY',size:.1,level:62290,stopLevel:61910,limitLevel:63430,openedAt:Date.now()-300000,closeAt:Date.now()+720000,currency:'USD'},{dealId:'demo-eur',epic:'DEMO.EUR.USD',instrumentName:'EUR / USD',direction:'SELL',size:2,level:10958.6,stopLevel:10978,limitLevel:10920,openedAt:Date.now()-120000,closeAt:Date.now()+480000,currency:'USD'}];S.pending=[{id:'demo-limit',epic:'DEMO.ETH.USD',direction:'BUY',size:.4,entry:2440,stopLevel:2410,targetLevel:2500,holdingMinutes:15,autoClose:true,status:'pending',reason:'Limit · inväntar simulerad fyllnad'}];S.closed=[{epic:'DEMO.GBP.USD',instrumentName:'GBP / USD',direction:'BUY',entry:13092,exit:13110,pnl:36,currency:'USD',openedAt:Date.now()-3600000,closedAt:Date.now()-2700000,costs:null,reason:'Take-profit · simulerad'},{epic:'DEMO.ETH.USD',instrumentName:'Ethereum / USD',entry:2480,exit:2455,pnl:-12.5,currency:'USD',openedAt:Date.now()-7200000,closedAt:Date.now()-6000000,costs:null,reason:'Stop-loss · simulerad'}];$('stop').value=S.market.quote.bid*.994;$('target').value=S.market.quote.offer*1.012;$('size').value=.1;notice('DESIGNLÄGE · alla konton, priser, signaler och affärer är lokala demodata. Inga mäklar- eller AI-anrop.');renderAll();renderChart(true);}
function simulateAnalysis(){const generation=S.generation;S.analysis={status:'running',steps:[{status:'Arbetar'}]};S.signals=[];renderAll();setTimeout(()=>{if(!S.simulation||generation!==S.generation)return;S.analysis={status:'running',steps:[{status:'Klar'},{status:'Arbetar'}]};renderSession();},500);setTimeout(()=>{if(!S.simulation||generation!==S.generation)return;S.analysis={status:'completed',completedAt:Date.now(),steps:[{status:'Klar'},{status:'Klar'},{status:'Klar'}]};S.signals=simulationSignals();renderAll();toast('Simulerad analys klar.');},1100);}
function setSimulationState(state){S.quoteState=state;S.connection={status:state==='disconnected'?'error':'connected'};if(state==='empty')S.signals=[];else if(state==='analyzing'){S.signals=[];S.analysis={status:'running',steps:[{status:'Klar'},{status:'Arbetar'}]};}else{S.signals=simulationSignals();S.analysis={status:'completed',completedAt:Date.now()};}if(S.current)S.market=simulationMarket(S.catalog.find(m=>m.epic===S.current));notice(`DESIGNLÄGE · ${$('demo-state').selectedOptions[0].textContent}. Alla data är simulerade.`);renderAll();}
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){toast(e.message);}};}
let importedSignals=[];
const importedMatchesAccount=row=>!row.stale&&row.environment===S.mode&&typeof row.generation==='string'&&row.generation===S.connection?.connectionGeneration;
function renderImportedSignals(){
  $('imported-signals-list').innerHTML=importedSignals.length?importedSignals.map(x=>`<article class="strategy-card"><div class="row"><b>${esc(nameOf(x.epic))}</b><span class="badge">Ej verifierat utkast</span></div><p>${x.direction==='BUY'?'Long':'Short'} · entry ${number(x.entryLevel,5)} · SL ${number(x.stopLevel,5)} · TP ${number(x.targetLevel,5)}</p><p>Giltig till ${esc(new Date(x.validUntil).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'}))} Stockholm${Date.now()>=x.validUntil?' · UTGÅNGEN':''}${!importedMatchesAccount(x)?' · ANNAN KONTOSESSION':''}</p><details><summary>Originaltext</summary><pre>${esc(x.sourceText??'Originaltext saknas')}</pre></details><div class="card-actions"><button data-import-copy="${esc(x.id)}" ${Date.now()>=x.validUntil||!importedMatchesAccount(x)?'disabled':''}>Kopiera till orderutkast</button><button data-import-delete="${esc(x.id)}">Ta bort</button></div></article>`).join(''):'<p class="field-note">Inga importerade signalutkast.</p>';
}
async function loadImportedSignals(){if(S.simulation){importedSignals=[];renderImportedSignals();return;}const generation=S.generation,result=await api(ig('imported-signals'));if(generation!==S.generation)return;importedSignals=result.signals??[];renderImportedSignals();}
$('import-signal-open').onclick=safe(async()=>{$('import-instrument').textContent=`IG ${S.mode.toUpperCase()} · ${S.current?nameOf(S.current):'Välj ett instrument i handelsytan innan du sparar.'}`;$('import-signal-form').dataset.epic=S.current??'';$('import-signal-form').querySelector('button[type="submit"]').disabled=S.simulation||!S.current;$('import-feedback').textContent=S.simulation?'Designläge: externa signaler sparas inte.':'';$('import-signal-dialog').showModal();await loadImportedSignals();});
$('import-signal-form').onsubmit=safe(async e=>{e.preventDefault();if(S.simulation)throw Error('Lämna designläget för att spara signaler.');const epic=$('import-signal-form').dataset.epic;if(!epic)throw Error('Välj ett instrument först.');const direction=$('import-direction').value,entryLevel=Number($('import-entry').value),stopLevel=Number($('import-stop').value),targetLevel=Number($('import-target').value),minutes=Number($('import-expiry').value),sign=direction==='BUY'?1:-1;if(![entryLevel,stopLevel,targetLevel].every(x=>Number.isFinite(x)&&x>0)||sign*(entryLevel-stopLevel)<=0||sign*(targetLevel-entryLevel)<=0)throw Error('Verifiera entry, stop loss och take profit för vald riktning.');if(!Number.isInteger(minutes)||minutes<1||minutes>1440)throw Error('Giltigheten måste vara 1–1440 minuter.');const generation=S.generation;await api('/api/ig/imported-signals',{method:'POST',body:{environment:S.mode,epic,sourceText:$('import-source').value,direction,entryLevel,stopLevel,targetLevel,validUntil:Date.now()+minutes*60000}});if(generation!==S.generation)return;await loadImportedSignals();$('import-feedback').textContent='Ej verifierat utkast sparat. Ingen order skickad.';});
document.addEventListener('click',safe(async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const id=b.dataset.importCopy??b.dataset.importDelete;if(!id)return;const row=importedSignals.find(x=>x.id===id);if(!row)return;if(b.dataset.importDelete){await api('/api/ig/imported-signals',{method:'DELETE',body:{environment:S.mode,id}});await loadImportedSignals();return;}if(!importedMatchesAccount(row))throw Error('Signalutkastet tillhör en tidigare eller annan kontoanslutning.');if(Date.now()>=row.validUntil)throw Error('Signalutkastet har gått ut.');const generation=S.generation,limit=$('import-copy-limit').checked;await chooseInstrument(row.epic);if(generation!==S.generation||S.current!==row.epic)return;if(!S.market||!quoteIsFresh(S.market))throw Error('Kopiering blockerad: färsk verifierad IG-kvot saknas.');if(!importedMatchesAccount(row))throw Error('Signalutkastet tillhör en tidigare eller annan kontoanslutning.');if(Date.now()>=row.validUntil)throw Error('Signalutkastet har gått ut.');S.direction=row.direction;S.orderType=limit?'LIMIT':'MARKET';$('limit').value=row.entryLevel;$('stop').value=row.stopLevel;$('target').value=row.targetLevel;recalculate();$('import-signal-dialog').close();toast('Ej verifierad signal kopierad till orderutkast. Granska separat; ingen order skickad.');}));
const strategyStatus=value=>({notBacktested:'EJ BACKTESTAD',unvalidated:'Ej validerad',not_applicable:'Gäller inte urvalet',insufficient_data:'Otillräcklig historik',invalid_data:'Ogiltigt underlag',evaluated:'Regler utvärderade',parked:'Parkerad'})[value]??value??'Status saknas';
const sourceLabel=source=>typeof source==='string'?source:source?.document??source?.json??source?.module??'Källa saknas';
const resultLabel=value=>value===true?'Uppfylld':value===false?'Ej uppfylld':'Ej utvärderad';
function renderAnalysisMemory(){
  const memory=S.analysisMemory;const count=memory?.recordCount;
  $('analysis-memory-count').textContent=Number.isInteger(count)?`· ${count} poster`:'';
  $('analysis-memory-content').innerHTML=!memory?'<p>Inget verifierat analysminne har hämtats för denna miljö.</p>':`<p>Status: ${esc(memory.status??'saknas')}${memory.reason?' · '+esc(memory.reason):''}</p>${memory.note?`<p>${esc(memory.note)}</p>`:''}${(memory.recentDecisions??[]).map(record=>`<article class="memory-decision"><div class="row"><b>${esc(new Date(record.at).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'}))} Stockholm</b><span>${esc(record.timeframe??'Tidsram saknas')}</span></div><p>${esc((record.epics??[]).map(nameOf).join(' · '))}</p><p>Strategier: ${esc((record.strategies??[]).map(x=>`${x.id} v${x.version??'?'}`).join(', ')||'Inga registrerade')}</p>${(record.decisions??[]).map(x=>`<p><b>${esc(nameOf(x.epic))} · ${esc(x.action)}</b> — ${esc(x.reason??'Motivering saknas')}</p>`).join('')}<small>JEV: ${esc(record.jev?.mode??'Källa saknas')} · ${record.jev?.available===true?'Tillgänglig':record.jev?.available===false?'Otillgänglig':'Status saknas'} · realiserat utfall ej verifierat</small></article>`).join('')||'<p>Inga sparade beslut att visa.</p>'}`;
}
function renderStrategyEvidence(){
  renderAnalysisMemory();
  const market=S.analysis?.jev?.market;
  $('jev-market-status').innerHTML=!market?'<p>JEV-marknadsbedömning: inget resultat tillgängligt för senaste analysen.</p>':`<h3>JEV · marknadsförkontroll</h3><p>${market.available?'Tillgänglig':'Otillgänglig'} · källa ${esc(market.mode??'saknas')} · modell ${esc(market.model??'saknas')} · ${Number.isFinite(market.latencyMs)?number(market.latencyMs,0)+' ms':'latens saknas'}</p><p>Ej kalibrerad bedömning. Ingen verifierad vinstsannolikhet.</p>${market.error||market.reason?`<p class="amber">${esc(market.error??market.reason)}</p>`:''}${(market.assessments??[]).map(x=>`<article class="strategy-assessment"><b>${esc(nameOf(x.epic))}</b><p>Regim: ${esc(x.regime??'saknas')} · riktning: ${esc(x.direction??'saknas')}</p><p>Strategimatchning: ${esc(typeof x.strategyFit==='string'?x.strategyFit:JSON.stringify(x.strategyFit??null))}</p><details><summary>Visa underlag</summary><pre>${esc(JSON.stringify(x,null,2))}</pre></details></article>`).join('')}`;
  const observations=S.analysis?.technical?.observations??[],comparisons=observations.filter(x=>Array.isArray(x.strategyComparisons)&&x.strategyComparisons.length),contexts=observations.filter(x=>x.strategyContext!==undefined&&x.strategyContext!==null);
  $('strategy-analysis-context').innerHTML=(comparisons.length?`<h3>Senaste regeljämförelse</h3><p>Deterministiska regler på analysens underlag. Ingen rankning efter framtida vinst.</p>${comparisons.map(x=>`<h4>${esc(nameOf(x.epic))}</h4><div class="strategy-table-wrap"><table class="strategy-table"><thead><tr><th>Strategi</th><th>Status</th><th>Entryregel</th><th>Exitregel</th><th>Stoppavstånd</th><th>Underlag</th></tr></thead><tbody>${x.strategyComparisons.map(c=>`<tr><td>${esc(c.name??c.id??c.strategyId)}</td><td>${esc(strategyStatus(c.status))}</td><td>${resultLabel(c.entrySignal)}</td><td>${resultLabel(c.exitCondition)}</td><td>${Number.isFinite(c.stopDistance)?number(c.stopDistance,5)+' prisenheter':'Saknas'}</td><td>${esc(c.reason??'Motivering saknas')}</td></tr>`).join('')}</tbody></table></div>`).join('')}`:'<p>Ingen strategijämförelse finns för senaste analysen.</p>')+(contexts.length?`<details><summary>Strategiunderlag från senaste analys</summary>${contexts.map(x=>`<pre>${esc(typeof x.strategyContext==='string'?x.strategyContext:JSON.stringify(x.strategyContext,null,2))}</pre>`).join('')}</details>`:'');
}
function renderStrategies(strategies=[],message=''){
  $('strategies-list').innerHTML=message?`<p>${esc(message)}</p>`:strategies.length?`<div class="strategy-table-wrap"><table class="strategy-table"><thead><tr><th>Strategi</th><th>Källa</th><th>Validering</th><th>Instrument / tidsram</th><th>Riktning</th></tr></thead><tbody>${strategies.map(x=>`<tr><td><b>${esc(x.name??x.id)}</b><details><summary>Regler & begränsningar</summary><p>${esc(x.description??(x.notes??[]).join(' '))}</p><pre>${esc(JSON.stringify({entry:x.entry,exit:x.exit,stop:x.stop},null,2))}</pre></details></td><td>${esc(sourceLabel(x.source))}</td><td><span class="amber">${esc(strategyStatus(x.status))}</span><small>Manuell granskning · ingen verifierad vinstprognos</small></td><td>${esc(x.instrument??'Se strategins omfattning')} · ${esc(x.timeframe??'Tidsram saknas')}</td><td>${esc(x.direction??x.side??'Saknas')}</td></tr>`).join('')}</tbody></table></div>`:'<p>Inga strategier returnerades av servern.</p>';
  renderStrategyEvidence();
}
async function loadStrategies(){const generation=S.generation;if(S.simulation){renderStrategies([],'Designläge: inget verkligt strategiregister har hämtats.');return;}renderStrategies([],'Hämtar strategiregister…');try{const result=await api(ig('strategies'));if(generation===S.generation)renderStrategies(result.strategies??[]);}catch(e){if(generation===S.generation)renderStrategies([],`Strategier kunde inte hämtas: ${e.message}`);}}
$('strategies-refresh').onclick=safe(loadStrategies);
function renderSchedules(){
  $('schedules-list').innerHTML=S.schedules.length?S.schedules.map(x=>`<article class="schedule-card"><div class="row"><b>${esc(x.name??'Agentsession')}</b><span class="badge">${x.enabled?'Aktivt':'Pausat'}</span></div><p>${esc(x.localTime??x.time)} · ${x.recurrence==='once'?esc(x.date):esc((x.weekdays??[]).map(d=>['','Mån','Tis','Ons','Tor','Fre','Lör','Sön'][d]).join(', '))} · Stockholm</p><small>${esc(x.epics?.map(nameOf).join(' · '))}</small><p>${x.nextRunAt?'Nästa: '+esc(new Date(x.nextRunAt).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'})):esc(x.lastError??x.status??'Inväntar aktivering')}</p><div class="card-actions"><button data-schedule-toggle="${esc(x.id)}">${x.enabled?'Pausa':'Aktivera'}</button><button data-schedule-delete="${esc(x.id)}">Ta bort</button></div></article>`).join(''):'<div class="empty-state">Inga schemalagda sessioner.</div>';
}
async function loadSchedules(){if(S.simulation){S.schedules=[];renderSchedules();return;}const result=await api(ig('schedules'));S.schedules=result.schedules??[];renderSchedules();}
async function openSchedules(){renderSelection();$('schedule-selection').textContent=`IG ${S.mode.toUpperCase()} · ${S.selected.size} valda: ${[...S.selected].map(nameOf).join(', ')}`;if(!$('schedule-date').value)$('schedule-date').value=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm'}).format(new Date());$('schedule-feedback').textContent=S.simulation?'Designläge: scheman kan inte sparas.':'';$('schedule-form').querySelector('button[type="submit"]').disabled=S.simulation||!S.selected.size;$('schedules-dialog').showModal();await loadSchedules();}
$('schedules-open').onclick=safe(openSchedules);$('catalog-schedule').onclick=safe(async()=>{$('catalog-dialog').close();await openSchedules();});
$('catalog-session').onclick=()=>{$('catalog-dialog').close();renderSelection();$('session-dialog').showModal();};
$('market-enrich').onclick=safe(async()=>{if(S.simulation)throw Error('Trend och sentiment hämtas endast för ett verifierat IG-konto.');if(!S.selected.size||S.selected.size>10)throw Error('Välj 1–10 instrument för fördjupning.');const generation=S.generation;$('market-enrich').disabled=true;try{for(const epic of S.selected){const data=await api(ig('directory/enrichment',{epic}));if(generation!==S.generation)return;const item=S.catalog.find(m=>m.epic===epic);if(item)Object.assign(item,data);}renderCatalog();toast('Fördjupning hämtad. Saknade underlag visas som saknas.');}finally{if(generation===S.generation)$('market-enrich').disabled=false;}});
$('market-ranking').onchange=renderCatalog;$('market-status').onchange=renderCatalog;
$('schedule-recurrence').onchange=()=>{const weekly=$('schedule-recurrence').value==='weekly';$('schedule-weekdays').hidden=!weekly;$('schedule-date').disabled=weekly;};
$('schedule-form').onsubmit=safe(async e=>{e.preventDefault();if(S.simulation)throw Error('Lämna designläget för att spara schema.');if(!S.selected.size)throw Error('Välj instrument först.');const weekdays=[...$('schedule-weekdays').querySelectorAll('input:checked')].map(x=>Number(x.value)),recurrence=$('schedule-recurrence').value;if(recurrence==='weekly'&&!weekdays.length)throw Error('Välj minst en veckodag.');const payload={...selection(),name:$('schedule-name').value.trim(),timezone:'Europe/Stockholm',localTime:$('schedule-time').value,date:recurrence==='once'?$('schedule-date').value:undefined,recurrence,weekdays,durationMinutes:Number($('schedule-duration').value),intervalMinutes:Number($('schedule-interval').value),enabled:true,maxPositions:1};await api('/api/ig/schedules',{method:'POST',body:payload});await loadSchedules();$('schedule-feedback').textContent='Schema sparat. Endast analys och manuella orderförslag.';});
document.addEventListener('click',safe(async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.scheduleToggle??b.dataset.scheduleDelete;if(!id)return;const row=S.schedules.find(x=>x.id===id);if(!row)return;if(b.dataset.scheduleDelete)await api('/api/ig/schedules',{method:'DELETE',body:{environment:S.mode,id}});else await api('/api/ig/schedules',{method:'POST',body:{id:row.id,environment:S.mode,enabled:!row.enabled}});await loadSchedules();}));
$('connect').onclick=safe(connect);$('analyze').onclick=safe(analyze);$('signals-refresh').onclick=safe(refresh);
let catalogSearchTimer;
$('search').oninput=()=>{S.instrumentRevision++;S.searchStatus='';renderInstruments();clearTimeout(searchTimer);searchTimer=setTimeout(safe(()=>discoverTerm($('search').value,'sidebar')),450);};$('catalog-search').oninput=()=>{S.catalogSearchStatus='';renderCatalog();clearTimeout(catalogSearchTimer);catalogSearchTimer=setTimeout(safe(()=>discoverTerm($('catalog-search').value,'catalog')),450);};
$('catalog-reload').onclick=safe(()=>loadCatalogView(true));
$('catalog-select-results').onclick=safe(async()=>{const next=new Set([...S.selected,...catalogRows().map(m=>m.epic)]);if(next.size>10)throw Error('Max 10 instrument per analys. Begränsa sökningen.');S.selected=next;renderInstruments();renderCatalog();await syncSelection();});
$('catalog-analyze').onclick=safe(async()=>{$('catalog-dialog').close();await analyze();});
$('select-all').onclick=safe(async()=>{const list=visibleMarkets();if(list.length>10)throw Error('IG-analysen har en befintlig gräns på 10 instrument. Begränsa sökningen.');if(new Set([...S.selected,...list.map(m=>m.epic)]).size>10)throw Error('Max 10 instrument per analys. Avmarkera först.');list.forEach(m=>S.selected.add(m.epic));renderInstruments();await syncSelection();});
$('selection-clear').onclick=safe(async()=>{S.selected.clear();renderInstruments();await syncSelection();});$('favorites-toggle').onclick=()=>{S.favoritesOnly=!S.favoritesOnly;renderInstruments();};
$('analysis-frame').onchange=safe(async()=>{S.analysisFrame=$('analysis-frame').value;await syncSelection();});
for(const id of ['size','stop','target','limit','holding','auto-close'])$(id).addEventListener('input',recalculate);
$('chart-type').onchange=()=>renderChart();$('indicator-toggle').onclick=()=>{indicator=!indicator;$('indicator-toggle').classList.toggle('positive',indicator);renderChart();};$('chart-fit').onclick=()=>chart?.timeScale().fitContent();
$('review-order').onclick=safe(reviewOrder);$('confirm-order').onclick=safe(async()=>{const callback=S.review;if(!callback)return;$('confirm-order').disabled=true;try{await callback();$('review-dialog').close();}finally{$('confirm-order').disabled=false;}});
$('settings-open').onclick=()=>{clearCredentialFields();void api('/api/ig/status').then(status=>{environmentStates=status.environments??{};renderEnvironmentStatus();}).catch(()=>{});$('ig-credentials-environment').value=S.mode;const disabled=!localHost||S.simulation||credentialsBusy;for(const id of ['ig-identifier','ig-password','ig-api-key','ig-credentials-environment','ig-credentials-submit'])$(id).disabled=disabled;if(!localHost)$('ig-credentials-feedback').textContent='Uppgifter kan bara sparas från localhost på denna dator.';else if(S.simulation)$('ig-credentials-feedback').textContent='Lämna designläget för att testa IG-inloggningen.';$('settings-dialog').showModal();void loadStrategies();};$('catalog-open').onclick=safe(async()=>{S.catalogView='all';renderCatalog();$('catalog-dialog').showModal();await loadCatalogView();});$('session-open').onclick=()=>{renderSelection();$('session-dialog').showModal();};
$('tools-open').onclick=()=>$('tools-dialog').showModal();
$('ig-credentials-environment').onchange=()=>{clearCredentialFields();$('ig-credentials-feedback').textContent=`IG ${$('ig-credentials-environment').value.toUpperCase()} valt. Tomma fält behåller endast denna miljös sparade uppgifter.`;};
$('ig-credentials-form').onsubmit=safe(async e=>{
  e.preventDefault();if(credentialsBusy||!localHost||S.simulation)return;
  const environment=$('ig-credentials-environment').value,payload={environment};
  for(const [id,key] of [['ig-identifier','identifier'],['ig-password','password'],['ig-api-key','apiKey']]){const value=$(id).value;if(value)payload[key]=key==='password'?value:value.trim();}
  const generation=S.generation;credentialsBusy=true;$('ig-credentials-feedback').textContent=`Sparar lokalt och testar IG ${environment.toUpperCase()}…`;
  for(const id of ['ig-identifier','ig-password','ig-api-key','ig-credentials-environment','ig-credentials-submit'])$(id).disabled=true;
  try{const result=await api('/api/ig/credentials',{method:'POST',body:payload});
    $('ig-password').value='';$('ig-api-key').value='';
    environmentStates=result.environments??result.status?.environments??environmentStates;renderEnvironmentStatus();
    const connection=result.environments?.[environment]??result.status?.environments?.[environment];
    $('ig-credentials-feedback').textContent=result.test?.ok===true&&connection?.status==='connected'?`IG ${environment.toUpperCase()} verifierat. Uppgifterna är sparade lokalt. Inga order skickades.`:`Uppgifterna sparades lokalt. IG-inloggningen kunde inte verifieras: ${connection?.error??result.test?.error??'kontrollera dina uppgifter och försök igen'}`;
    if(generation===S.generation&&environment===S.mode){await refresh();if(S.connection?.status==='connected')await restoreChart();}
  }catch(e){$('ig-credentials-feedback').textContent=`IG-anslutningen kunde inte verifieras: ${e.message}`;}
  finally{credentialsBusy=false;$('ig-password').value='';$('ig-api-key').value='';for(const id of ['ig-identifier','ig-password','ig-api-key','ig-credentials-environment','ig-credentials-submit'])$(id).disabled=!localHost||S.simulation;}
});
$('simulation-toggle').onclick=safe(async()=>{S.simulation=!S.simulation;clearAccountState();S.quoteState='ready';$('simulation-states').hidden=!S.simulation;$('simulation-toggle').textContent=S.simulation?'Lämna designläge':'Aktivera designläge';$('demo-state').value='ready';if(S.simulation)loadSimulation();else{connectRealtime();renderAll();notice('Designläget avslutat. IG-kontot verifieras på nytt.');await refresh();}});
$('demo-state').onchange=()=>setSimulationState($('demo-state').value);
$('session-form').onsubmit=safe(async e=>{e.preventDefault();if(!S.selected.size)throw Error('Välj instrument före sessionen');S.analysisFrame=$('session-frame').value;$('analysis-frame').value=S.analysisFrame;S.maxPositions=Number($('session-max').value);const durationMinutes=Number($('session-duration').value),intervalMinutes=Number($('session-frequency').value),payload={...selection(),horizonMinutes:Number($('session-holding').value),durationMinutes,intervalMinutes,maxPositions:S.maxPositions};
  if(S.simulation){S.session={...payload,status:'running',startedAt:Date.now(),endsAt:Date.now()+durationMinutes*60000,nextRunAt:Date.now()+intervalMinutes*60000};simulateAnalysis();}else{await syncSelection();S.session=await api('/api/ig/session',{method:'POST',body:payload});await refresh();}renderSession();$('session-dialog').close();toast(S.simulation?'Simulerad agentsession startad':'IG-agentsession startad · manuella orderförslag');});
$('session-stop').onclick=safe(async()=>{if(S.simulation){S.session.status='stopped';}else{await api('/api/ig/session',{method:'DELETE',body:{environment:S.mode}});await refresh();}renderSession();toast('Session stoppad. Öppna positioner stängs inte automatiskt.');});
$('kill').onclick=safe(async()=>{if(S.simulation){if(S.session)S.session.status='stopped';S.analysis={status:'failed',error:'Simulerat nödstopp'};S.signals=[];renderAll();toast('Simulerat nödstopp aktivt');}else{await api('/api/kill-switch',{method:'POST',body:{active:true}});await api('/api/ig/session',{method:'DELETE',body:{environment:S.mode}});await refresh();toast('Kill switch aktiverad. Inga positioner har stängts.');}});
$('trade-filter').onchange=renderTrades;$('period-filter').onchange=renderTrades;
document.addEventListener('click',safe(async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
  if(d.tool){$('tools-dialog').close();if(d.tool==='markets')$('markets-open').click();else if(d.tool==='session')$('session-open').click();else if(d.tool==='settings')$('settings-open').click();else{showTradingView();document.querySelector('.workspace').dataset.panel='activity';if(['open','closed'].includes(d.tool))S.tradeTab=d.tool;renderTrades();$('signals').scrollIntoView({block:'nearest'});}return;}if(d.close){$(d.close).close();return;}if(d.mode||d.accountMode){if($('settings-dialog').open){clearCredentialFields();$('settings-dialog').close();}await switchMode(d.mode??d.accountMode);return;}if(d.category){await changeCategory(d.category);return;}if(d.catalogCategory){if(['all','favorites'].includes(d.catalogCategory)){S.catalogView=d.catalogCategory;$('catalog-search').value='';renderCatalog();await loadCatalogView();}else await changeCategory(d.catalogCategory);return;}
  if(d.panel){document.querySelector('.workspace').dataset.panel=d.panel;document.querySelectorAll('[data-panel]').forEach(x=>{if(x.tagName==='BUTTON')x.classList.toggle('active',x.dataset.panel===d.panel);});return;}
  if(d.chart){showTradingView();await chooseInstrument(d.chart);if($('catalog-dialog').open)$('catalog-dialog').close();return;}if(d.star){S.favorites.has(d.star)?S.favorites.delete(d.star):S.favorites.add(d.star);if(S.simulation)localStorage.setItem('trading-workspace-favorites',JSON.stringify([...S.favorites]));else{try{const result=await api('/api/ig/preferences',{method:'POST',body:{environment:S.mode,favorites:[...S.favorites],revision:S.preferencesRevision}});const prefs=result.preferences??result;S.favorites=new Set(prefs.favorites??[]);S.preferencesRevision=prefs.revision??S.preferencesRevision;}catch(e){await refresh();throw e;}}renderInstruments();renderCatalog();subscribeRealtime();return;}
  if(d.frame){S.chartFrame=d.frame;document.querySelectorAll('[data-frame]').forEach(x=>x.classList.toggle('active',x.dataset.frame===d.frame));if(S.current)await chooseInstrument(S.current,{reset:false});return;}
  if(d.direction){S.direction=d.direction;recalculate();return;}if(d.orderType){S.orderType=d.orderType;recalculate();return;}if(d.percent){const t=ticket(),size=sizeForCapitalRisk({...t,percent:Number(d.percent)});if(size==null)throw Error('Riskandel kräver verifierat punktvärde, konto och stop-loss.');$('size').value=size;recalculate();return;}
  if(d.trades){S.tradeTab=d.trades;renderTrades();return;}if(d.copy){await copySignal(d.copy);return;}if(d.double){await doubleUp(d.double);return;}if(d.roll){rollOver(d.roll);return;}if(d.closePosition){closePosition(d.closePosition);return;}
  if(d.selectCategory){const markets=S.catalog.filter(m=>kind(m)===d.selectCategory);if(new Set([...S.selected,...markets.map(m=>m.epic)]).size>10)throw Error('Befintlig IG-analysgräns är 10 instrument');markets.forEach(m=>S.selected.add(m.epic));renderCatalog();renderInstruments();await syncSelection();return;}
  if(d.fill){const p=S.pending.find(p=>p.id===d.fill);if(!S.simulation||!p)return;if(S.quoteState!=='ready')throw Error('Simulerad fyllnad stoppad av datastatus');if(S.positions.length>=S.maxPositions)throw Error('Max samtidiga positioner nådd');const generation=S.generation;p.status='accepted';renderTrades();setTimeout(()=>{if(!S.simulation||generation!==S.generation)return;S.pending=S.pending.filter(x=>x.id!==p.id);addSimulationPosition(p);renderTrades();renderChart();toast('Simulerad order fylld · position öppen');},300);return;}
  if(d.cancel){S.pending=S.pending.filter(p=>p.id!==d.cancel);renderTrades();}
}));
document.addEventListener('change',safe(async e=>{const epic=e.target.dataset.select;if(!epic)return;if(e.target.checked&&!S.selected.has(epic)&&S.selected.size>=10){e.target.checked=false;throw Error('Max 10 instrument per analys. Avmarkera ett instrument först.');}e.target.checked?S.selected.add(epic):S.selected.delete(epic);renderInstruments();renderCatalog();await syncSelection();}));
setInterval(safe(async()=>{
  if(!S.simulation){if(document.hidden)return;renderChart();if(!realtimeHealthy())await refresh();else{renderHeader();recalculate();renderSignals();renderSession();}if(Date.now()-catalogResumeAt>=60000){const categories=$('catalog-dialog').open&&['favorites','all'].includes(S.catalogView)?['forex','crypto']:[$('catalog-dialog').open?S.catalogView:S.category];const next=categories.find(c=>S.catalogState[c]?.status==='partial'&&S.catalogState[c]?.remainingSearches>0);if(next)await loadCatalog(next);}return;}
  if(S.market&&S.quoteState!=='stale'&&S.quoteState!=='disconnected')S.market.quote.receivedAt=Date.now();
  if(S.session?.status==='running'){if(Date.now()>=S.session.endsAt){S.session.status='completed';}else if(Date.now()>=S.session.nextRunAt&&S.quoteState==='ready'){S.session.nextRunAt=Date.now()+S.session.intervalMinutes*60000;simulateAnalysis();}}
  // Avslut simuleras först efter kvotkontroll; ett fel lämnar positionen öppen.
  for(const p of [...S.positions])if(p.closeAt&&Date.now()>=p.closeAt&&!p.closeError){if(S.quoteState==='stale'||S.quoteState==='disconnected'||S.quoteState==='order-error'){p.closeError='Tidsstängning misslyckades · demodata';continue;}const calc=positionPnl(p);S.closed.unshift({...p,entry:p.level,exit:calc.current,pnl:calc.pnl,costs:null,closedAt:Date.now(),reason:'Planerad tidsstängning · simulerad'});S.positions=S.positions.filter(x=>x.dealId!==p.dealId);}
  renderTrades();renderSignals();renderSession();recalculate();
}),5000);
initializeChart();renderAll();void startWorkspace();
