import {mergeStreamCandle} from './streamCandles.mjs';
import {frames,quoteIsFresh} from './model.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const chartScale=frame=>['1m','3m','15m','30m'].includes(frame)?'1MINUTE':frame==='5m'?'5MINUTE':['1h','4h'].includes(frame)?'HOUR':null;
export function chartSubscriptions(primary,extras){return [...new Map([primary,...extras].filter(x=>x?.epic&&chartScale(x.frame)).map(x=>{const scale=chartScale(x.frame);return [`${x.epic}:${scale}`,{epic:x.epic,scale}];})).values()];}
export function shouldRefreshChart(slot,now,transportHealthy){return !slot.loading&&now-slot.lastLoad>=60000&&(!chartScale(slot.frame)||slot.error||!transportHealthy||now-(slot.bars.at(-1)?.receivedAt??0)>=60000);}
export function createMultiCharts({state,request,onSubscriptions,openPrimary,simulationCandles,simulationMarket,healthy}){
 const grid=document.getElementById('chart-grid'),host=document.getElementById('extra-charts'),symbolLink=document.getElementById('link-chart-symbols'),frameLink=document.getElementById('link-chart-frames');
 let count=1,mode=null,generation=null,connection=null,primaryKey='',queue=Promise.resolve(),catalogKey='';
 const slots=Array.from({length:3},(_,i)=>({id:i+1,epic:null,frame:'15m',type:'candles',market:null,bars:[],parts:new Map(),revision:0,chart:null,candles:null,line:null,sma:null,indicator:false,loading:false,error:null,lastLoad:0}));
 const active=()=>slots.slice(0,count-1),current=s=>state().generation===generation&&slots.includes(s)&&s.id<count;
 const safe=fn=>event=>Promise.resolve(fn(event)).catch(()=>{});
 function save(){try{localStorage.setItem(`ig-chart-layout-${mode}`,JSON.stringify({count,symbolLinked:symbolLink.checked,frameLinked:frameLink.checked,slots:slots.map(({epic,frame,type,indicator})=>({epic,frame,type,indicator}))}));}catch{}}
 function restore(){let saved;try{saved=JSON.parse(localStorage.getItem(`ig-chart-layout-${mode}`));}catch{}count=[1,2,3,4].includes(saved?.count)?saved.count:1;symbolLink.checked=saved?.symbolLinked===true;frameLink.checked=saved?.frameLinked===true;slots.forEach((s,i)=>{const p=saved?.slots?.[i];s.epic=typeof p?.epic==='string'&&/^[A-Za-z0-9._-]{1,100}$/.test(p.epic)?p.epic:null;s.frame=Object.hasOwn(frames,p?.frame)?p.frame:'15m';s.type=p?.type==='line'?'line':'candles';s.indicator=p?.indicator===true;});}
 function clear(){for(const s of slots){s.revision++;s.market=null;s.latestQuote=null;s.bars=[];s.parts.clear();s.loading=false;s.lastLoad=0;s.error=null;paint(s);}}
 function build(s){const tile=document.createElement('article');tile.className='chart-tile extra-chart-tile';tile.dataset.chartSlot=s.id;tile.hidden=true;
  tile.innerHTML=`<div class="chart-tile-caption"><span>0${s.id+1} · Jämförelsediagram</span><button class="extra-open-primary" title="Visa instrumentet i huvuddiagrammet">Till huvuddiagram ↗</button></div><div class="extra-chart-controls"><select class="extra-symbol" aria-label="Instrument diagram ${s.id+1}"><option value="">Välj instrument</option></select><select class="extra-frame" aria-label="Intervall diagram ${s.id+1}">${Object.keys(frames).map(f=>`<option>${f}</option>`).join('')}</select><select class="extra-type" aria-label="Typ diagram ${s.id+1}"><option value="candles">Candles</option><option value="line">Linje</option></select><button class="extra-indicator">SMA 20</button><button class="extra-fit" title="Anpassa diagram">↔</button><button class="extra-retry" title="Hämta underlag igen">↻</button></div><div class="extra-chart-heading"><b class="extra-name">Välj instrument</b><span class="extra-price">—</span></div><div class="chart-body"><div class="extra-chart-canvas"></div><div class="extra-chart-error">Välj instrument</div></div><div class="extra-chart-status">Inga prisdata</div>`;
  host.append(tile);s.tile=tile;s.symbol=tile.querySelector('.extra-symbol');s.frameInput=tile.querySelector('.extra-frame');s.typeInput=tile.querySelector('.extra-type');
  s.symbol.addEventListener('change',safe(()=>{if(symbolLink.checked){symbolLink.checked=false;}s.epic=s.symbol.value||null;save();onSubscriptions();return load(s);}));
  s.frameInput.addEventListener('change',safe(()=>{if(frameLink.checked)frameLink.checked=false;s.frame=s.frameInput.value;save();onSubscriptions();return load(s);}));
  s.typeInput.addEventListener('change',()=>{s.type=s.typeInput.value;save();paint(s);});
  tile.querySelector('.extra-open-primary').addEventListener('click',safe(()=>s.epic&&openPrimary(s.epic)));
  tile.querySelector('.extra-fit').addEventListener('click',()=>s.chart?.timeScale().fitContent());
  tile.querySelector('.extra-retry').addEventListener('click',safe(()=>load(s)));
  tile.querySelector('.extra-indicator').addEventListener('click',()=>{s.indicator=!s.indicator;save();paint(s);});
  new ResizeObserver(entries=>{for(const e of entries)if(e.contentRect.width>0&&e.contentRect.height>0){ensureChart(s);s.chart?.resize(e.contentRect.width,e.contentRect.height);}}).observe(tile.querySelector('.extra-chart-canvas'));
 }
 function ensureChart(s){if(s.chart||!window.LightweightCharts||s.tile.hidden)return;const green='#22c55e',red='#ef4444';s.chart=window.LightweightCharts.createChart(s.tile.querySelector('.extra-chart-canvas'),{layout:{background:{color:'#000000'},textColor:'#8493a8',fontSize:9},grid:{vertLines:{color:'#141b24'},horzLines:{color:'#141b24'}},rightPriceScale:{borderColor:'#253143'},timeScale:{borderColor:'#253143',timeVisible:true},crosshair:{mode:0}});s.candles=s.chart.addCandlestickSeries({upColor:green,downColor:red,wickUpColor:green,wickDownColor:red,borderVisible:false});s.line=s.chart.addLineSeries({color:green,lineWidth:2,visible:false});s.sma=s.chart.addLineSeries({color:'#dbb674',lineWidth:1,priceLineVisible:false,lastValueVisible:false,visible:false});paint(s);}
 function paint(s,fit=false){if(!s.tile)return;const q=s.market?.quote,now=Date.now();const label=s.market?.name||s.market?.instrument?.name||state().catalog.find(m=>m.epic===s.epic)?.name||s.epic||'Välj instrument';s.tile.querySelector('.extra-name').textContent=label;s.tile.querySelector('.chart-tile-caption span').textContent=`0${s.id+1} · ${label} · ${s.epic??'—'} · ${s.frame} · ${state().simulation?'DEMODATA':'IG '+state().mode.toUpperCase()}${s.loading?' · laddar':''}`;const precision=s.market?.instrument?.decimalPlacesFactor;const dp=Number.isInteger(precision)&&precision>=0&&precision<=8?precision:2;
  s.tile.querySelector('.extra-price').textContent=Number.isFinite(q?.bid)?new Intl.NumberFormat('sv-SE',{maximumFractionDigits:dp,minimumFractionDigits:dp}).format(q.bid):'—';
  const empty=s.tile.querySelector('.extra-chart-error');empty.hidden=s.bars.length>0;empty.textContent=s.loading?'Hämtar verifierade IG-ljus…':s.error??(s.epic?'Inga verifierade ljus':'Välj instrument');
  const status=s.tile.querySelector('.extra-chart-status'),live=state().streaming?.status==='CONNECTED:WS-STREAMING'&&now-(s.bars.at(-1)?.receivedAt??0)<60000,fresh=quoteIsFresh(s.market,now);
  status.textContent=s.error??(state().simulation?'DEMODATA · inga externa anrop':`${live?'IG WebSocket · live mid-ljus':s.bars.length?'IG historiska mid-ljus':'Inväntar underlag'}${s.bars.at(-1)?.partial?' · delvis ljus':''} · ${fresh?`prisålder ${Math.max(0,Math.floor((now-q.observedAt)/1000))} s${q.delayVerification?' · REST-verifierad fördröjning':''}`:'kvot ej färsk/verifierad'}`);status.classList.toggle('amber',!fresh&&!state().simulation);
  s.frameInput.value=s.frame;s.typeInput.value=s.type;s.tile.querySelector('.extra-indicator').classList.toggle('active',s.indicator);
  if(!s.chart)return;const bars=s.bars.map(b=>({time:Math.floor(b.openTime/1000),open:b.open,high:b.high,low:b.low,close:b.close})).sort((a,b)=>a.time-b.time).filter((b,i,a)=>(!i||b.time!==a[i-1].time)&&[b.open,b.high,b.low,b.close].every(Number.isFinite));
  const priceFormat={type:'price',precision:dp,minMove:10**(-dp)};s.candles.applyOptions({visible:s.type==='candles',priceFormat});s.line.applyOptions({visible:s.type==='line',priceFormat});s.sma.applyOptions({visible:s.indicator,priceFormat});s.candles.setData(bars);s.line.setData(bars.map((b,i)=>({time:b.time,value:b.close,color:b.close>=(bars[i-1]?.close??b.open)?'#22c55e':'#ef4444'})));const averages=[];for(let i=19;i<bars.length;i++)averages.push({time:bars[i].time,value:bars.slice(i-19,i+1).reduce((sum,b)=>sum+b.close,0)/20});s.sma.setData(averages);if(fit)s.chart.timeScale().fitContent();
 }
 function load(s,{preserve=false}={}){if(!s.epic){s.loading=false;paint(s);return Promise.resolve();}const st=state(),binding={generation:st.generation,connection:st.connection?.connectionGeneration,mode:st.mode,epic:s.epic,frame:s.frame,revision:++s.revision};s.loading=true;s.error=null;if(!preserve){s.market=null;s.latestQuote=null;s.bars=[];s.parts.clear();}paint(s);
  const valid=()=>current(s)&&state().generation===binding.generation&&state().mode===binding.mode&&state().connection?.connectionGeneration===binding.connection&&s.revision===binding.revision&&s.epic===binding.epic&&s.frame===binding.frame;
  const job=queue.catch(()=>{}).then(async()=>{if(!valid()||!s.epic)return;try{let market,bars;if(state().simulation){const item=state().catalog.find(m=>m.epic===s.epic);if(!item)throw Error('Instrumentet saknas i designläget');market=simulationMarket(item);bars=simulationCandles(item);}else{if(state().connection?.status!=='connected')throw Error('Anslut IG för att visa diagram');const params=new URLSearchParams({environment:binding.mode,epic:binding.epic});market=await request(`/api/ig/market?${params}`);if(!valid())return;if(market?.epic!==binding.epic)throw Error('Instrumentet i svaret matchar inte diagrammet');const history=await request(`/api/ig/candles?${params}&timeframe=${binding.frame}&limit=100`).then(value=>({value}),error=>({error:error.message}));if(!valid())return;bars=history.value?.candles??[];if(history.error)s.error=`Historik saknas: ${history.error}`;}if(!valid())return;
   // Historik får aldrig skriva över en nyare mottagen streamkvot eller samma pågående streamljus.
   const quote=s.latestQuote??s.market?.quote;if(quote?.observedAt>=(market.quote?.observedAt??0))market={...market,quote};const streams=s.bars.filter(b=>b.receivedAt&&(!b.closed||b.openTime>=(bars.at(-1)?.openTime??Infinity)));const merged=new Map(bars.map(b=>[b.openTime,b]));for(const b of streams)if(!merged.get(b.openTime)?.closed)merged.set(b.openTime,b);s.market=market;s.bars=[...merged.values()].sort((a,b)=>a.openTime-b.openTime);s.lastLoad=Date.now();
  }catch(e){if(valid())s.error=`Underlag ej verifierat: ${e.message}`;}finally{if(valid()){s.loading=false;s.lastLoad=Date.now();paint(s,!preserve);}}});queue=job;return job;
 }
 function sync(){const st=state(),newConnection=st.connection?.connectionGeneration??null;
  if(mode!==st.mode||generation!==st.generation||connection!==newConnection){mode=st.mode;generation=st.generation;connection=newConnection;primaryKey='';catalogKey='';clear();restore();}
  grid.dataset.count=String(count);document.querySelectorAll('[data-chart-count]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.chartCount)===count);b.setAttribute('aria-pressed',String(Number(b.dataset.chartCount)===count));});slots.forEach(s=>{s.tile.hidden=s.id>=count;});
  const primary=`${st.current}:${st.chartFrame}`,key=st.catalog.map(m=>`${m.epic}:${m.name}`).join('|');
  for(const s of active()){let changed=false;if(!s.epic){s.epic=st.catalog.filter(m=>['crypto','forex'].includes(m.category)||m.type==='CURRENCIES')[s.id]?.epic??st.current;changed=true;}if(symbolLink.checked&&s.epic!==st.current){s.epic=st.current;changed=true;}if(frameLink.checked&&s.frame!==st.chartFrame){s.frame=st.chartFrame;changed=true;}
   if(key!==catalogKey||!Array.from(s.symbol.options).some(o=>o.value===s.epic)){const rows=st.catalog.filter(m=>m.type==='CURRENCIES'||['crypto','forex'].includes(m.category));s.symbol.innerHTML='<option value="">Välj instrument</option>'+rows.map(m=>`<option value="${esc(m.epic)}">${esc(m.name??m.epic)}</option>`).join('')+(s.epic&&!rows.some(m=>m.epic===s.epic)?`<option value="${esc(s.epic)}">${esc(s.epic)}</option>`:'');}s.symbol.value=s.epic??'';ensureChart(s);
   if(changed){s.revision++;s.loading=false;s.error=null;}if((changed||(!s.market&&!s.error&&!s.lastLoad))&&!s.loading&&s.epic&&(st.simulation||st.connection?.status==='connected'))void load(s);paint(s);
  }
  catalogKey=key;if(primary!==primaryKey){primaryKey=primary;save();}onSubscriptions();
 }
 function onMessage(kind,data){for(const s of active()){if(s.epic!==data.epic||data.generation&&data.generation!==state().connection?.connectionGeneration)continue;if(kind==='quote'){if(!s.latestQuote||!(s.latestQuote.observedAt>data.observedAt))s.latestQuote=data;if(s.market&&!(s.market.quote?.observedAt>data.observedAt))s.market={...s.market,quote:data};paint(s);}if(kind==='candle'&&data.scale===chartScale(s.frame)){const seconds=frames[s.frame],source=data.scale==='HOUR'?3600:data.scale==='5MINUTE'?300:60,bucket=Math.floor(data.openTime/(seconds*1000))*seconds*1000,prior=s.bars.find(b=>b.openTime===bucket),merged=mergeStreamCandle(prior,data,seconds,source,s.parts);s.bars=[...s.bars.filter(b=>b.openTime!==bucket),merged].sort((a,b)=>a.openTime-b.openTime).slice(-500);for(const old of s.parts.keys())if(old<bucket-seconds*2000)s.parts.delete(old);paint(s);if(seconds!==source&&data.closed&&data.openTime+source*1000>=bucket+seconds*1000&&!merged.closed)void load(s,{preserve:true});}}}
 for(const s of slots)build(s);
 document.querySelectorAll('[data-chart-count]').forEach(b=>b.addEventListener('click',()=>{count=Number(b.dataset.chartCount);for(const s of slots)if(s.id>=count){s.revision++;s.loading=false;s.parts.clear();}save();sync();}));
 symbolLink.addEventListener('change',()=>{save();sync();});frameLink.addEventListener('change',()=>{save();sync();});
 setInterval(()=>{for(const s of active()){paint(s);if(s.epic&&shouldRefreshChart(s,Date.now(),healthy()&&state().streaming?.status==='CONNECTED:WS-STREAMING')&&(state().simulation||state().connection?.status==='connected'))void load(s,{preserve:true});}},5000);
 return {sync,onMessage,epics:()=>active().map(s=>s.epic).filter(Boolean),charts:()=>active().map(s=>({epic:s.epic,frame:s.frame})),reset:clear};
}
