export function createResearch({state,api,esc,toast,showView}){
 const $=id=>document.getElementById(id);let data=null,binding='',loading=null,busy=false;
 const identity=()=>JSON.stringify([state.mode,state.generation,state.connection?.connectionGeneration]);
 const payload=()=>({environment:state.mode,connectionGeneration:data.connectionGeneration,revision:data.revision});
 function reset(){if(binding===identity())return;binding=identity();data=null;loading=null;render();}
 function render(){
  $('research-context').textContent=`IG ${state.mode.toUpperCase()} · ${state.current??'Inget instrument valt'} · Forskningschatt`;
  $('research-messages').innerHTML=data?.messages.length?data.messages.map(m=>`<article class="research-message ${esc(m.role)}"><b>${esc(({user:'Du',technical:'Teknisk analytiker',head:'Hanna / Head Trader'})[m.role]??m.role)}</b><p>${esc(m.text)}</p><small>${esc(new Date(m.at).toLocaleString('sv-SE'))}</small></article>`).join(''):'<div class="research-empty"><h2>Ditt agentteam</h2><p>Diskutera strategier, förklara en signal eller planera ett test. JEV gör förkontroll, sedan svarar Teknisk analytiker och Hanna.</p><p>Lägg till källor i Strategy Library. Chatten skickar inga order.</p></div>';
  const sources=data?.sources??[];$('research-sources').innerHTML=sources.length?sources.map(s=>`<article class="library-source"><b>${esc(s.name)}</b><small>${s.kind==='link'?'Länkreferens · ej inläst':'Textfil · '+s.content.length+' tecken'}</small>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Öppna källan ↗</a>`:''}</article>`).join(''):'<p class="muted">Inga källor sparade.</p>';
  const baseline=$('research-baseline'),selected=baseline.value;baseline.innerHTML=(data?.baselines??[]).map(s=>`<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.timeframe)}</option>`).join('');if([...baseline.options].some(o=>o.value===selected))baseline.value=selected;
  $('research-strategies').innerHTML=(data?.strategies??[]).map(s=>`<article class="library-strategy"><div class="row"><h2>${esc(s.name)}</h2><span class="badge">Utkast · inte aktiverad</span></div><p>${esc(s.specification)}</p><small>Basstrategi: ${esc(data.baselines.find(b=>b.id===s.baselineId)?.name??s.baselineId)} · ${s.sourceIds.length} källor</small><button data-research-test="${esc(s.id)}">Kontrollera basregler på valt instrument</button>${s.tests.map(t=>`<details><summary>${esc(new Date(t.at).toLocaleString('sv-SE'))} · ${esc(t.epic)} · ${esc(t.timeframe)}</summary><p>${esc(t.note)}</p><pre>${esc(JSON.stringify(t.result,null,2))}</pre></details>`).join('')}</article>`).join('')||'<p class="research-empty">Spara en idé med regler och basstrategi. Underlag och regelkontroller sparas tillsammans.</p>';
  $('research-send').disabled=busy||!data||state.simulation;$('research-send').textContent=busy?'Agentteamet arbetar…':'Skicka till agentteamet';for(const b of document.querySelectorAll('[data-research-test]'))b.disabled=busy||!state.current;
 }
 async function load(){reset();if(state.simulation){$('research-status').textContent='Designläge: inget verkligt bibliotek eller AI-anrop.';render();return;}if(loading)return loading;const own=identity();loading=(async()=>{try{const result=await api('/api/ig/research?environment='+state.mode);if(identity()===own){data=result;render();$('research-status').textContent='Synkat med servern · kontoavgränsat och sparat på disk';}}catch(e){if(identity()===own)$('research-status').textContent=e.message;}finally{if(identity()===own)loading=null;}})();return loading;}
 async function mutate(body,path='research',expected=identity()){if(busy||state.simulation||identity()!==expected)return;const own=expected;await load();if(busy||!data||identity()!==own)return;busy=true;render();try{const result=await api('/api/ig/'+path,{method:'POST',body:{...payload(),...body}});if(identity()===own){data=result;render();$('research-status').textContent='Sparat och synkat med servern';}}catch(e){if(identity()===own){$('research-status').textContent=e.message;toast(e.message);}}finally{busy=false;if(identity()===own)render();}}
 async function openChat(){reset();$('research-chat').hidden=false;await load();$('research-message').focus();}
 $('chat-open').onclick=openChat;$('chat-floating').onclick=openChat;$('research-close').onclick=()=>{$('research-chat').hidden=true;};
 $('library-open').onclick=async()=>{showView('library');await load();};$('research-chat-link').onclick=openChat;
 $('research-chat-form').onsubmit=async e=>{e.preventDefault();const input=$('research-message'),message=input.value;if(!message.trim())return;await mutate({message,page:document.querySelector('.workspace-nav [aria-current="page"]')?.textContent.trim()??'Handelsyta',epic:state.current},'research/chat');if(data?.messages.at(-3)?.text===message.trim())input.value='';};
 $('research-file').onchange=async e=>{const own=identity(),file=e.target.files[0];if(!file)return;if(file.size>20000||!/\.(txt|md|json|csv)$/i.test(file.name)){toast('Välj TXT, MD, JSON eller CSV, högst 20 kB.');e.target.value='';return;}await mutate({action:'source',kind:'file',name:file.name,content:await file.text()},'research',own);e.target.value='';};
 $('research-link-form').onsubmit=async e=>{e.preventDefault();await mutate({action:'source',kind:'link',name:$('research-link-name').value,url:$('research-url').value});};
 $('research-strategy-form').onsubmit=async e=>{e.preventDefault();await mutate({action:'strategy',name:$('research-name').value,specification:$('research-spec').value,baselineId:$('research-baseline').value,sourceIds:(data?.sources??[]).map(s=>s.id)});};
 $('research-strategies').onclick=async e=>{const b=e.target.closest('[data-research-test]');if(!b)return;if(!state.current){toast('Välj först ett instrument i handelsytan.');return;}await mutate({id:b.dataset.researchTest,epic:state.current},'research/test');};
 return {sync(revision){reset();$('research-context').textContent=`IG ${state.mode.toUpperCase()} · ${state.current??'Inget instrument valt'} · Forskningschatt`;if(!data&&(!$('library-page').hidden||!$('research-chat').hidden)&&!busy)void load();if(data&&revision!==null&&revision!==undefined&&revision!==data.revision&&!busy)void load();},reset,load};
}
